[parse]
sourcefile=[ "surpratk.cpp" ]

[buttons]
names = [
    { names="Shot,Jump", machine="suratk" },
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[header]
info = """ Header to identify the PCB type
        Byte 0 = 4 - Surprise Attack
                 """
data = [
    { machine="suratk", offset=0, data="04" },
]

[ROM]
regions = [
    { name="maincpu",  machine="parodius" },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="k052109",  start="JTFRAME_BA2_START", width=32, rename="tiles" }, # tiles
    { name="k053244",  start="JTFRAME_BA3_START", width=32, rename="obj", machine="suratk" }, # sprites
]

order = [ "maincpu", "tiles", "obj" ]
