[parse.machine]
name="test85"
description="TEST85 ROM download test"
year="2026"
manufacturer="Jotego"

[[parse.machine.rom]]
name="test85.bin"
region="maincpu"
size=0x40
status="nodump"

[parse.machine.display]
rotate=0
width=256
height=224

[parse.machine.input]
players=1

[[parse.machine.input.control]]
type="joy"
buttons=2

[rom]
regions=[
    { name="maincpu", custom={ dev="65c02" }, rom_len=0x40, no_offset=true },
]

order=[
    "maincpu",
]
