#!/bin/bash

OUTDIR=mra
ALTDIR=_alternatives/"_The Speed Rumbler"

mkdir -p $OUTDIR/"$ALTDIR"

mame2dip srumbler.xml -outdir $OUTDIR -altfolder "$ALTDIR" \
    -corebuttons 2 -buttons "Shoot,Exit car"