#!/bin/bash

OUTDIR=mra
ALTDIR=_alternatives/"_The Speed Rumbler"

mkdir -p $OUTDIR/"$ALTDIR"

mame2dip srumbler.xml -outdir $OUTDIR -altfolder "$ALTDIR" \
    -rbf jtrumble \
    -rename char=gfx1 -swapbytes char \
    -rename scr=gfx2 -order-roms scr 0 4 1 5 2 6 3 7 -frac 1 scr 2 \
    -rename obj=gfx3 -order-roms obj 0 2 4 6 1 3 5 7 -frac 1 obj 4 \
    -corebuttons 2 -buttons "Shoot,Exit car"