#!/bin/bash

OUTDIR=mra
ALTDIR=_alternatives/"_The Speed Rumbler"

mkdir -p $OUTDIR/"$ALTDIR"

mame2dip srumbler.xml -outdir $OUTDIR -altfolder "$ALTDIR" \
    -rbf jtrumble \
    -rename char=gfx1 -swapbytes char \
    -rename scr=gfx2 -order-roms scr 4 0 5 1 6 2 7 3 -frac 1 scr 2 \
    -rename obj=gfx3 -order-roms obj 6 4 2 0 7 5 3 1 -frac 1 obj 4 \
    -corebuttons 2 -buttons "Shoot,Exit car"