[parse]
sourcefile=[ "pacland.cpp" ]

[buttons]
names=[
	{ machine="pacland", names="Jump" },
]

[dipsw]
rename=[ {name="Bonus Life", to="Bonus" }, ]

[ROM]
regions = [
	{ name="maincpu"                             },
	{ name="mcusub",   start="JTFRAME_BA1_START" },
	{ name="fg_chars", start="JTFRAME_BA2_START" },
	{ name="bg_chars", start="BG_START"          },
	{ name="sprites",  start="JTFRAME_BA3_START", width=16, sequence=[0,2,1,3] },
	{ name="mcu",      start="JTFRAME_PROM_START"},
	{ name="proms" },
]

order=["maincpu", "mcusub",
	"fg_chars","bg_chars","sprites",
       "mcu","proms"
]