[global]
author=["jotego"]

[parse]
sourcefile=[ "1943.cpp" ]
skip.bootlegs=true

[Audio]
volume = [
    { machine="1943kai", value=0x60 },
    { machine="1943", value=0x51 },
    { machine="1943mii", value=0x63 },
]

[buttons]
names=[
    { names="Shoot,Bomb" }
]

[ROM]
regions=[
    { name="maincpu", no_offset=true },
    { name="audiocpu"},
    { name="mcu", skip=true },
    { name="gfx1", reverse=true },
    { name="tilerom", reverse=true, no_offset=true, start="JTFRAME_BA1_START" },
    { name="gfx2", width=16, sequence=[4,0,5,1,6,2,7,3], no_offset=true, start="JTFRAME_BA2_START" },
    { name="gfx3", width=16, reverse=true, no_offset=true },
    { name="gfx4", width=16, sequence=[4,0,5,1,6,2,7,3], no_offset=true, start="JTFRAME_BA3_START" },
    { name="proms", sequence=[4,7,0,6,1,2,10,3,11,9,8,5], no_offset=true },
]

order=[ "maincpu", "audiocpu", "gfx1",
    "tilerom", "gfx2", "gfx3", "gfx4",
    "proms"
]