// jtpspike_game_sdram.v is automatically generated by JTFRAME
// Do not modify it
// Do not add it to git

`ifndef JTFRAME_COLORW
`define JTFRAME_COLORW 4
`endif

`ifndef JTFRAME_BUTTONS
`define JTFRAME_BUTTONS 2
`endif

module jtpspike_game_sdram(
    `include "jtframe_common_ports.inc"
    `include "jtframe_mem_ports.inc"
);

/* verilator lint_off WIDTH */
localparam [25:0] BA1_START  =`ifdef JTFRAME_BA1_START  `JTFRAME_BA1_START  `else 26'd0 `endif;
localparam [25:0] BA2_START  =`ifdef JTFRAME_BA2_START  `JTFRAME_BA2_START  `else 26'd0 `endif;
localparam [25:0] BA3_START  =`ifdef JTFRAME_BA3_START  `JTFRAME_BA3_START  `else 26'd0 `endif;
localparam [25:0] PROM_START =`ifdef JTFRAME_PROM_START `JTFRAME_PROM_START `else 26'd0 `endif;
localparam [25:0] HEADER_LEN =`ifdef JTFRAME_HEADER     `JTFRAME_HEADER     `else 26'd0 `endif;
localparam        SDRAMW     =`ifdef JTFRAME_SDRAM_XL 25 `elsif JTFRAME_SDRAM_LARGE 24 `else 23 `endif;
localparam        IOCTL_AW   =`ifdef JTFRAME_SDRAM_XL 27 `else 26 `endif;
/* verilator lint_on WIDTH */


parameter SCR0_OFFSET = `SCR0_START>>1;
parameter SND_OFFSET = (`SND_START -`JTFRAME_BA1_START)>>1;
parameter OBJ0_OFFSET = (`OBJ0_START-`JTFRAME_BA2_START)>>1;
parameter PCMB_OFFSET = (`PCMB_START-`JTFRAME_BA3_START)>>1;

// Audio channels 
wire signed [15:0] fm_l, fm_r;
wire mute;
// Additional ports
wire [15:0] lut1_dout;
wire [15:0] mix_pal;
wire [1:0] ram_we;
wire [15:0] scr_vram;
wire [1:0] oram_we;
wire [1:0] oram1_we;
wire [13:1] ram2_addr;
wire [12:1] vram1_addr;
wire [1:0] lut1_we;
wire [15:1] lut1_addr;
wire [15:0] pal_dout;
wire [11:1] rascr_addr;
wire [11:1] ras_addr;
wire [15:1] lut_addr;
wire [15:0] objl_dout;
wire [15:0] objr_dout;
wire [15:0] oram1_dout;
wire [15:0] objr1_dout;
wire [15:0] objl1_dout;
wire [15:1] ram_addr;
wire [12:1] scr_addr;
wire [15:0] scr1_vram;
wire [10:1] oram_addr;
wire [11:1] mix_addr;
wire [15:0] vram_dout;
wire [10:1] objr_addr;
wire [11:1] pal_addr;
wire [15:0] oram_dout;
wire [15:0] lut_dout;
wire [1:0] pal_we;
wire [12:1] vram_addr;
wire [12:1] scr1v_addr;
wire [15:0] rascr_dout;
wire [1:0] rascr_we;
wire [15:0] main_dout;
wire [15:0] ras_dout;
wire [15:1] objl1_addr;
wire [15:0] vram1_dout;
wire [1:0] vram1_we;
wire [10:1] oram1_addr;
wire [10:1] objr1_addr;
wire [15:0] ram_dout;
wire [15:0] ram2_dout;
wire [1:0] ram2_we;
wire [1:0] vram_we;
wire [1:0] lut_we;
wire [15:1] objl_addr;

// BRAM buses


















// SDRAM buses

wire [19:2] scr0_addr;
wire [31:0] scr0_data;
wire        scr0_cs, scr0_ok;
wire [19:1] main_addr;
wire [15:0] main_data;
wire        main_cs, main_ok;
wire [16:0] snd_addr;
wire [ 7:0] snd_data;
wire        snd_cs, snd_ok;
wire [20:2] obj1_addr;
wire [31:0] obj1_data;
wire        obj1_cs, obj1_ok;
wire [19:0] pcma_addr;
wire [ 7:0] pcma_data;
wire        pcma_cs, pcma_ok;
wire [21:2] obj0_addr;
wire [31:0] obj0_data;
wire        obj0_cs, obj0_ok;
wire [18:0] pcmb_addr;
wire [ 7:0] pcmb_data;
wire        pcmb_cs, pcmb_ok;
wire [20:2] scr1_addr;
wire [31:0] scr1_data;
wire        scr1_cs, scr1_ok;
wire        prom_we, header;
wire [SDRAMW-2:0] raw_addr, post_addr;
wire [SDRAMW-2:0] ioctl_prog_addr   = ioctl_addr[SDRAMW-2:0];
wire [IOCTL_AW-1:0] pre_addr, dwnld_addr, ioctl_addr_noheader;
wire [ 7:0] post_data;
wire [15:0] raw_data;
wire [ 7:0] pcb_id;
wire        pass_io;
// Clock enable signals
wire fm_cen; 
wire snd_cen; 
wire snd4_cen; 
wire gfx4_en, gfx8_en, gfx16_en, gfx16b_en, gfx16c_en, ioctl_dwn;

assign pass_io = header | ioctl_ram;
assign ioctl_addr_noheader = `ifdef JTFRAME_HEADER header ? ioctl_addr : ioctl_addr - HEADER_LEN `else ioctl_addr `endif ;
`ifdef JTFRAME_SDRAM_CACHE
assign burst_addr = { (SDRAMW-1){1'b0} };
assign burst_ba   = 2'd0;
assign burst_rd   = 1'b0;
assign burst_wr   = 1'b0;
assign burst_din  = 16'd0;
`endif

wire rst_h, rst24_h, rst48_h, hold_rst;

/* verilator tracing_off */
jtframe_rsthold u_hold(
    .rst    ( rst       ),
    .clk    ( clk       ),
    .hold   ( hold_rst  ),
    .rst_h  ( rst_h     ),
    .rst24  ( rst24     ),
    .clk24  ( clk24     ),
    .rst24_h( rst24_h   )
`ifdef JTFRAME_CLK48 ,
    .rst48  ( rst48     ),
    .clk48  ( clk48     ),
    .rst48_h( rst48_h   )
`endif
);
/* verilator tracing_on */
jtpspike_game u_game(
    .rst        ( rst_h     ),
    .clk        ( clk       ),
    .rst24      ( rst24_h   ),
    .clk24      ( clk24     ),
`ifdef JTFRAME_CLK48
    .rst48      ( rst48_h   ),
    .clk48      ( clk48     ),
`endif
    .rst96      ( rst96     ),
    .clk96      ( clk96     ),
    // Audio channels
    .fm_l   ( fm_l    ),
    .fm_r   ( fm_r    ),
    
    .snd_en         ( snd_en        ),
    .snd_vol        ( snd_vol       ),
    .fm_cen    ( fm_cen    ), 
    .snd_cen    ( snd_cen    ), 
    .snd4_cen    ( snd4_cen    ), 

    .pxl2_cen       ( pxl2_cen      ),
    .pxl_cen        ( pxl_cen       ),
    .red            ( red           ),
    .green          ( green         ),
    .blue           ( blue          ),
    .LHBL           ( LHBL          ),
    .LVBL           ( LVBL          ),
    .HS             ( HS            ),
    .VS             ( VS            ),
    // cabinet I/O
    .cab_1p   ( cab_1p  ),
    .coin     ( coin    ),
    .joystick1    ( joystick1        ), .joystick2    ( joystick2        ),
    .joystick3    ( joystick3        ), .joystick4    ( joystick4        ), `ifdef JTFRAME_MOUSE
    .mouse_1p     ( mouse_1p         ), .mouse_2p     ( mouse_2p         ), .mouse_strobe ( mouse_strobe ), `endif `ifdef JTFRAME_LIGHTGUN
    .gun_1p_x     ( gun_1p_x         ), .gun_1p_y     ( gun_1p_y         ),
    .gun_2p_x     ( gun_2p_x         ), .gun_2p_y     ( gun_2p_y         ), `endif `ifdef JTFRAME_SPINNER
    .spinner_1p   ( spinner_1p       ), .spinner_2p   ( spinner_2p       ), `endif
    .joyana_l1    ( joyana_l1        ), .joyana_l2    ( joyana_l2        ),
    .joyana_l3    ( joyana_l3        ), .joyana_l4    ( joyana_l4        ),
    .joyana_r1    ( joyana_r1        ), .joyana_r2    ( joyana_r2        ),
    .joyana_r3    ( joyana_r3        ), .joyana_r4    ( joyana_r4        ),
    .dial_x       ( dial_x           ), .dial_y       ( dial_y           ),
    // DIP switches
    .status         ( status        ),
    .dipsw          ( dipsw         ),
    .service        ( service       ),
    .tilt           ( tilt          ),
    .dip_pause      ( dip_pause     ),
    .dip_flip       ( dip_flip      ),
    .dip_test       ( dip_test      ),
    .dip_fxlevel    ( dip_fxlevel   ),
    // Ports declared in mem.yaml
    .lut1_dout   ( lut1_dout ),
    .mix_pal   ( mix_pal ),
    .ram_we   ( ram_we ),
    .scr_vram   ( scr_vram ),
    .oram_we   ( oram_we ),
    .oram1_we   ( oram1_we ),
    .ram2_addr   ( ram2_addr ),
    .vram1_addr   ( vram1_addr ),
    .lut1_we   ( lut1_we ),
    .lut1_addr   ( lut1_addr ),
    .pal_dout   ( pal_dout ),
    .rascr_addr   ( rascr_addr ),
    .ras_addr   ( ras_addr ),
    .lut_addr   ( lut_addr ),
    .objl_dout   ( objl_dout ),
    .objr_dout   ( objr_dout ),
    .oram1_dout   ( oram1_dout ),
    .objr1_dout   ( objr1_dout ),
    .objl1_dout   ( objl1_dout ),
    .ram_addr   ( ram_addr ),
    .scr_addr   ( scr_addr ),
    .scr1_vram   ( scr1_vram ),
    .oram_addr   ( oram_addr ),
    .mix_addr   ( mix_addr ),
    .vram_dout   ( vram_dout ),
    .objr_addr   ( objr_addr ),
    .pal_addr   ( pal_addr ),
    .oram_dout   ( oram_dout ),
    .lut_dout   ( lut_dout ),
    .pal_we   ( pal_we ),
    .vram_addr   ( vram_addr ),
    .scr1v_addr   ( scr1v_addr ),
    .rascr_dout   ( rascr_dout ),
    .rascr_we   ( rascr_we ),
    .main_dout   ( main_dout ),
    .ras_dout   ( ras_dout ),
    .objl1_addr   ( objl1_addr ),
    .vram1_dout   ( vram1_dout ),
    .vram1_we   ( vram1_we ),
    .oram1_addr   ( oram1_addr ),
    .objr1_addr   ( objr1_addr ),
    .ram_dout   ( ram_dout ),
    .ram2_dout   ( ram2_dout ),
    .ram2_we   ( ram2_we ),
    .vram_we   ( vram_we ),
    .lut_we   ( lut_we ),
    .objl_addr   ( objl_addr ),
    // Memory interface - SDRAM
    .scr0_addr ( scr0_addr ),
    .scr0_cs   ( scr0_cs   ),
    .scr0_ok   ( scr0_ok   ),
    .scr0_data ( scr0_data ),
    
    .main_addr ( main_addr ),
    .main_cs   ( main_cs   ),
    .main_ok   ( main_ok   ),
    .main_data ( main_data ),
    
    .snd_addr ( snd_addr ),
    .snd_cs   ( snd_cs   ),
    .snd_ok   ( snd_ok   ),
    .snd_data ( snd_data ),
    
    .obj1_addr ( obj1_addr ),
    .obj1_cs   ( obj1_cs   ),
    .obj1_ok   ( obj1_ok   ),
    .obj1_data ( obj1_data ),
    
    .pcma_addr ( pcma_addr ),
    .pcma_cs   ( pcma_cs   ),
    .pcma_ok   ( pcma_ok   ),
    .pcma_data ( pcma_data ),
    
    .obj0_addr ( obj0_addr ),
    .obj0_cs   ( obj0_cs   ),
    .obj0_ok   ( obj0_ok   ),
    .obj0_data ( obj0_data ),
    
    .pcmb_addr ( pcmb_addr ),
    .pcmb_cs   ( pcmb_cs   ),
    .pcmb_ok   ( pcmb_ok   ),
    .pcmb_data ( pcmb_data ),
    
    .scr1_addr ( scr1_addr ),
    .scr1_cs   ( scr1_cs   ),
    .scr1_ok   ( scr1_ok   ),
    .scr1_data ( scr1_data ),
    
    // Memory interface - BRAM

    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
`ifdef JTFRAME_SRAM
    // SRAM
    .sram_addr  ( sram_addr     ),
    .sram_din   ( sram_din      ),
    .sram_dout  ( sram_dout     ),
    .sram_wen   ( sram_wen      ),
    .sram_dsn   ( sram_dsn      ),
    .sram_ok    ( sram_ok       ),
`endif

`ifdef JTFRAME_SAVEGAME
    // Save/Load
    .sav_change ( sav_change    ),
    .sav_wait   ( sav_wait      ),
    .sav_done   ( sav_done      ),
    .sav_wr     ( sav_wr        ),
    .sav_ack    ( sav_ack       ),
    .sav_din    ( sav_din       ),
    .sav_dout   ( sav_dout      ),
    .sav_addr   ( sav_addr      ),
`endif
    // PROM writting
    .ioctl_addr   ( pass_io ? ioctl_addr       : ioctl_addr_noheader  ),
    .prog_addr    ( pass_io ? ioctl_prog_addr : raw_addr      ),
    .prog_data    ( pass_io ? ioctl_dout       : raw_data[7:0] ),
    .prog_we      ( pass_io ? ioctl_wr         : prog_we       ),
    .prog_ba      ( prog_ba        ), // prog_ba supplied in case it helps re-mapping addresses
    .prom_we      ( pass_io ? 1'b0 : prom_we ),
`ifdef JTFRAME_HEADER
    .header       ( header         ),
`endif
`ifdef JTFRAME_IOCTL_RD
    .ioctl_din    ( ioctl_din      ),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ), `endif
    .ioctl_ram    ( ioctl_ram      ),
    .ioctl_cart   ( ioctl_cart     ),
    // Debug
    .debug_bus    ( debug_bus      ),
    .debug_view   ( debug_view     ),
`ifdef JTFRAME_STATUS
    .st_addr      ( st_addr        ),
    .st_dout      ( st_dout        ),
`endif
`ifdef JTFRAME_LF_BUFFER
    .game_vrender( game_vrender  ),
    .game_hdump  ( game_hdump    ),
    .ln_addr     ( ln_addr       ),
    .ln_data     ( ln_data       ),
    .ln_done     ( ln_done       ),
    .ln_hs       ( ln_hs         ),
    .ln_dout     ( ln_dout       ),
    .ln_pxl      ( ln_pxl        ),
    .ln_v        ( ln_v          ),
    .ln_vs       ( ln_vs         ),
    .ln_lvbl     ( ln_lvbl       ),
    .ln_we       ( ln_we         ),
    .fb_keep     ( fb_keep       ),
`ifdef JTFRAME_LF_ZOOM
    .h_step      ( h_step        ),
    .v_step      ( v_step        ),
`endif
`endif
    .gfx_en      ( gfx_en        )
);
/* verilator tracing_off */
assign dwnld_busy = ioctl_rom | prom_we | prog_we; // prom_we is really just for sims
assign dwnld_addr = ioctl_addr;
`ifdef JTFRAME_SDRAM_XL
wire [26:0] dwnld_addr_wide = dwnld_addr;
`else
wire [26:0] dwnld_addr_wide = {1'b0,dwnld_addr};
`endif
assign prog_addr = raw_addr;
assign prog_data = raw_data;
assign gfx4_en   = 0;
assign gfx8_en   = 0;
assign gfx16_en  = 0;
assign gfx16b_en = 0;
assign gfx16c_en = 0;
assign ioctl_dwn = ioctl_rom | ioctl_cart;
`ifdef VERILATOR_KEEP_SDRAM /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_dwnld #(
    .SDRAMW     ( SDRAMW       ),
`ifdef JTFRAME_HEADER
    .HEADER    ( `JTFRAME_HEADER   ),
`endif
`ifdef JTFRAME_BA1_START
    .BA1_START ( BA1_START ),
`endif
`ifdef JTFRAME_BA2_START
    .BA2_START ( BA2_START ),
`endif
`ifdef JTFRAME_BA3_START
    .BA3_START ( BA3_START ),
`endif
`ifdef JTFRAME_PROM_START
    .PROM_START( PROM_START ),
`endif
    .SWAB      ( 1),
    .GFX8B0    ( 0),
    .GFX16B0   ( 0)
) u_dwnld(
    .clk          ( clk            ),
    .ioctl_rom    ( ioctl_dwn      ),
    .ioctl_addr   ( dwnld_addr_wide),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .gfx4_en      ( gfx4_en        ),
    .gfx8_en      ( gfx8_en        ),
    .gfx16_en     ( gfx16_en       ),
    .gfx16b_en    ( gfx16b_en      ),
    .gfx16c_en    ( gfx16c_en      ),
    .prog_addr    ( raw_addr       ),
    .prog_data    ( raw_data       ),
    .prog_mask    ( prog_mask      ), // active low
    .prog_we      ( prog_we        ),
    .prog_rd      ( prog_rd        ),
    .prog_ba      ( prog_ba        ),
    .prom_we      ( prom_we        ),
    .header       ( header         ),
    .sdram_ack    ( prog_ack       )
);

jtframe_headerbyte #(.AW(6)) u_pcbid(
    .clk          ( clk            ),
    .header       ( header         ),
    .ioctl_addr   ( ioctl_addr[5:0]),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .dout         ( pcb_id         )
);
`ifdef VERILATOR_KEEP_SDRAM /* verilator tracing_on */ `else /* verilator tracing_off */ `endif


jtframe_rom_2slots #(
    .SDRAMW(SDRAMW-1),
    // scr0
    .SLOT0_OFFSET(SCR0_OFFSET[SDRAMW-2:0]),
    .SLOT0_AW(19),
    .SLOT0_DW(32), 
    // main
    .SLOT1_AW(19),
    .SLOT1_DW(16)
`ifdef JTFRAME_BA0_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
`endif
`ifdef JTFRAME_BA0_LEN
    ,.SLOT0_BURSTLEN(`JTFRAME_BA0_LEN)
`else
    ,.SLOT0_BURSTLEN(32)
`endif
`ifdef JTFRAME_BA0_LEN
    ,.SLOT1_BURSTLEN(`JTFRAME_BA0_LEN)
`else
    ,.SLOT1_BURSTLEN(32)
`endif
) u_bank0(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( { scr0_addr, 1'b0 } ),
    .slot0_dout  ( scr0_data  ),
    .slot0_cs    ( scr0_cs    ),
    .slot0_ok    ( scr0_ok    ),
    
    .slot1_addr  ( main_addr  ),
    .slot1_dout  ( main_data  ),
    .slot1_cs    ( main_cs    ),
    .slot1_ok    ( main_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[0]  ),
    .sdram_rd    ( ba_rd[0]   ),
    .sdram_addr  ( ba0_addr   ),
    .data_dst    ( ba_dst[0]  ),
    .data_rdy    ( ba_rdy[0]  ),
    .data_read   ( data_read  )
);
assign ba_wr[0] = 0;
assign ba0_din  = 0;
assign ba0_dsn  = 3;
jtframe_rom_2slots #(
    .SDRAMW(SDRAMW-1),
    // snd
    .SLOT0_OFFSET(SND_OFFSET[SDRAMW-2:0]),
    .SLOT0_AW(17),
    .SLOT0_DW( 8), 
    // obj1
    .SLOT1_AW(20),
    .SLOT1_DW(32)
`ifdef JTFRAME_BA1_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
`endif
`ifdef JTFRAME_BA1_LEN
    ,.SLOT0_BURSTLEN(`JTFRAME_BA1_LEN)
`else
    ,.SLOT0_BURSTLEN(32)
`endif
`ifdef JTFRAME_BA1_LEN
    ,.SLOT1_BURSTLEN(`JTFRAME_BA1_LEN)
`else
    ,.SLOT1_BURSTLEN(32)
`endif
) u_bank1(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( snd_addr  ),
    .slot0_dout  ( snd_data  ),
    .slot0_cs    ( snd_cs    ),
    .slot0_ok    ( snd_ok    ),
    
    .slot1_addr  ( { obj1_addr, 1'b0 } ),
    .slot1_dout  ( obj1_data  ),
    .slot1_cs    ( obj1_cs    ),
    .slot1_ok    ( obj1_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[1]  ),
    .sdram_rd    ( ba_rd[1]   ),
    .sdram_addr  ( ba1_addr   ),
    .data_dst    ( ba_dst[1]  ),
    .data_rdy    ( ba_rdy[1]  ),
    .data_read   ( data_read  )
);
assign ba_wr[1] = 0;
assign ba1_din  = 0;
assign ba1_dsn  = 3;
jtframe_rom_2slots #(
    .SDRAMW(SDRAMW-1),
    // pcma
    .SLOT0_AW(20),
    .SLOT0_DW( 8), 
    // obj0
    .SLOT1_OFFSET(OBJ0_OFFSET[SDRAMW-2:0]),
    .SLOT1_AW(21),
    .SLOT1_DW(32)
`ifdef JTFRAME_BA2_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
`endif
`ifdef JTFRAME_BA2_LEN
    ,.SLOT0_BURSTLEN(`JTFRAME_BA2_LEN)
`else
    ,.SLOT0_BURSTLEN(32)
`endif
`ifdef JTFRAME_BA2_LEN
    ,.SLOT1_BURSTLEN(`JTFRAME_BA2_LEN)
`else
    ,.SLOT1_BURSTLEN(32)
`endif
) u_bank2(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( pcma_addr  ),
    .slot0_dout  ( pcma_data  ),
    .slot0_cs    ( pcma_cs    ),
    .slot0_ok    ( pcma_ok    ),
    
    .slot1_addr  ( { obj0_addr, 1'b0 } ),
    .slot1_dout  ( obj0_data  ),
    .slot1_cs    ( obj0_cs    ),
    .slot1_ok    ( obj0_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[2]  ),
    .sdram_rd    ( ba_rd[2]   ),
    .sdram_addr  ( ba2_addr   ),
    .data_dst    ( ba_dst[2]  ),
    .data_rdy    ( ba_rdy[2]  ),
    .data_read   ( data_read  )
);
assign ba_wr[2] = 0;
assign ba2_din  = 0;
assign ba2_dsn  = 3;
jtframe_rom_2slots #(
    .SDRAMW(SDRAMW-1),
    // pcmb
    .SLOT0_OFFSET(PCMB_OFFSET[SDRAMW-2:0]),
    .SLOT0_AW(19),
    .SLOT0_DW( 8), 
    // scr1
    .SLOT1_AW(20),
    .SLOT1_DW(32)
`ifdef JTFRAME_BA3_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
`endif
`ifdef JTFRAME_BA3_LEN
    ,.SLOT0_BURSTLEN(`JTFRAME_BA3_LEN)
`else
    ,.SLOT0_BURSTLEN(32)
`endif
`ifdef JTFRAME_BA3_LEN
    ,.SLOT1_BURSTLEN(`JTFRAME_BA3_LEN)
`else
    ,.SLOT1_BURSTLEN(32)
`endif
) u_bank3(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( pcmb_addr  ),
    .slot0_dout  ( pcmb_data  ),
    .slot0_cs    ( pcmb_cs    ),
    .slot0_ok    ( pcmb_ok    ),
    
    .slot1_addr  ( { scr1_addr, 1'b0 } ),
    .slot1_dout  ( scr1_data  ),
    .slot1_cs    ( scr1_cs    ),
    .slot1_ok    ( scr1_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[3]  ),
    .sdram_rd    ( ba_rd[3]   ),
    .sdram_addr  ( ba3_addr   ),
    .data_dst    ( ba_dst[3]  ),
    .data_rdy    ( ba_rdy[3]  ),
    .data_read   ( data_read  )
);
assign ba_wr[3] = 0;
assign ba3_din  = 0;
assign ba3_dsn  = 3;
assign hold_rst=0;
`ifdef JTFRAME_PROM_START
localparam JTFRAME_PROM_START=`JTFRAME_PROM_START;
`endif

// BRAM for ram
jtframe_ram16 #(
    .AW(16-1),
    .LATCH_IN(0),
    .LATCH_OUT(0),
    .ENDIAN(0)
) u_bram_ram(
    .clk    ( clk  ),
    .addr   ( ram_addr ),
    .data   ( main_dout ),
    .we     ( ram_we ),
    .q      ( ram_dout )
);

// BRAM for ram2
jtframe_ram16 #(
    .AW(14-1),
    .LATCH_IN(0),
    .LATCH_OUT(0),
    .ENDIAN(0)
) u_bram_ram2(
    .clk    ( clk  ),
    .addr   ( ram2_addr ),
    .data   ( main_dout ),
    .we     ( ram2_we ),
    .q      ( ram2_dout )
);

// Dual port BRAM for vram and scr
jtframe_dual_ram16 #(
    .AW(13-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(1),
    .SIMFILE("vram.bin")
) u_bram_vram(
    // Port 0 - vram
    .clk0   ( clk ),
    .addr0  ( vram_addr ),
    .data0  ( main_dout  ),
    .we0    (  vram_we ), 
    .q0     ( vram_dout ),
    // Port 1 - scr
    .clk1   ( clk ),
    .data1  ( 16'd0 ),
    .addr1  ( scr_addr[12:1] ),
    .we1    ( 2'd0  ),
    .q1     ( scr_vram )
);
// Dual port BRAM for vram1 and scr1v
jtframe_dual_ram16 #(
    .AW(13-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(1),
    .SIMFILE("vram1.bin")
) u_bram_vram1(
    // Port 0 - vram1
    .clk0   ( clk ),
    .addr0  ( vram1_addr ),
    .data0  ( main_dout  ),
    .we0    (  vram1_we ), 
    .q0     ( vram1_dout ),
    // Port 1 - scr1v
    .clk1   ( clk ),
    .data1  ( 16'd0 ),
    .addr1  ( scr1v_addr[12:1] ),
    .we1    ( 2'd0  ),
    .q1     ( scr1_vram )
);
// Dual port BRAM for rascr and ras
jtframe_dual_ram16 #(
    .AW(12-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(1),
    .SIMFILE("rascr.bin")
) u_bram_rascr(
    // Port 0 - rascr
    .clk0   ( clk ),
    .addr0  ( rascr_addr ),
    .data0  ( main_dout  ),
    .we0    (  rascr_we ), 
    .q0     ( rascr_dout ),
    // Port 1 - ras
    .clk1   ( clk ),
    .data1  ( 16'd0 ),
    .addr1  ( ras_addr[11:1] ),
    .we1    ( 2'd0  ),
    .q1     ( ras_dout )
);
// Dual port BRAM for oram and objr
jtframe_dual_ram16 #(
    .AW(11-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(1),
    .SIMFILE("oram.bin")
) u_bram_oram(
    // Port 0 - oram
    .clk0   ( clk ),
    .addr0  ( oram_addr ),
    .data0  ( main_dout  ),
    .we0    (  oram_we ), 
    .q0     ( oram_dout ),
    // Port 1 - objr
    .clk1   ( clk ),
    .data1  ( 16'd0 ),
    .addr1  ( objr_addr[10:1] ),
    .we1    ( 2'd0  ),
    .q1     ( objr_dout )
);
// Dual port BRAM for oram1 and objr1
jtframe_dual_ram16 #(
    .AW(11-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(1),
    .SIMFILE("oram1.bin")
) u_bram_oram1(
    // Port 0 - oram1
    .clk0   ( clk ),
    .addr0  ( oram1_addr ),
    .data0  ( main_dout  ),
    .we0    (  oram1_we ), 
    .q0     ( oram1_dout ),
    // Port 1 - objr1
    .clk1   ( clk ),
    .data1  ( 16'd0 ),
    .addr1  ( objr1_addr[10:1] ),
    .we1    ( 2'd0  ),
    .q1     ( objr1_dout )
);
// Dual port BRAM for lut and objl
jtframe_dual_ram16 #(
    .AW(16-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(1),
    .SIMFILE("lut.bin")
) u_bram_lut(
    // Port 0 - lut
    .clk0   ( clk ),
    .addr0  ( lut_addr ),
    .data0  ( main_dout  ),
    .we0    (  lut_we ), 
    .q0     ( lut_dout ),
    // Port 1 - objl
    .clk1   ( clk ),
    .data1  ( 16'd0 ),
    .addr1  ( objl_addr[15:1] ),
    .we1    ( 2'd0  ),
    .q1     ( objl_dout )
);
// Dual port BRAM for lut1 and objl1
jtframe_dual_ram16 #(
    .AW(16-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(1),
    .SIMFILE("lut1.bin")
) u_bram_lut1(
    // Port 0 - lut1
    .clk0   ( clk ),
    .addr0  ( lut1_addr ),
    .data0  ( main_dout  ),
    .we0    (  lut1_we ), 
    .q0     ( lut1_dout ),
    // Port 1 - objl1
    .clk1   ( clk ),
    .data1  ( 16'd0 ),
    .addr1  ( objl1_addr[15:1] ),
    .we1    ( 2'd0  ),
    .q1     ( objl1_dout )
);
// Dual port BRAM for pal and mix
jtframe_dual_ram16 #(
    .AW(12-1),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .ENDIAN(1),
    .SIMFILE("pal.bin")
) u_bram_pal(
    // Port 0 - pal
    .clk0   ( clk ),
    .addr0  ( pal_addr ),
    .data0  ( main_dout  ),
    .we0    (  pal_we ), 
    .q0     ( pal_dout ),
    // Port 1 - mix
    .clk1   ( clk ),
    .data1  ( 16'd0 ),
    .addr1  ( mix_addr[11:1] ),
    .we1    ( 2'd0  ),
    .q1     ( mix_pal )
);


// Clock enable generation
// 7999998 = 57272720*44/315 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(1),.NUM(44),.DEN(315),.MFREQ(57272)) u_cen0_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( (pcma_cs & ~pcma_ok) | (pcmb_cs & ~pcmb_ok)    ),
    .cen    ( { fm_cen } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

// 4999999 = 57272720*11/126 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(1),.NUM(11),.DEN(126),.MFREQ(57272)) u_cen1_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( (snd_cs & ~snd_ok)    ),
    .cen    ( { snd_cen } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

// 3999999 = 57272720*22/315 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(1),.NUM(22),.DEN(315),.MFREQ(57272)) u_cen2_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( (snd_cs & ~snd_ok)    ),
    .cen    ( { snd4_cen } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

`ifndef NOSOUND
`ifdef VERILATOR_KEEP_AUDIO /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
assign mute=0;

jtframe_rcmix #(
    .W0(16),
    .STEREO0( 1),
    .STEREO1( 0),
    .STEREO2( 0),
    .STEREO3( 0),
    .STEREO4( 0),
    .STEREO5( 0),
    .DCRM0  ( 0),
    .DCRM1  ( 0),
    .DCRM2  ( 0),
    .DCRM3  ( 0),
    .DCRM4  ( 0),
    .DCRM5  ( 0),
    .STEREO ( 0),
    // Fractional cen for 192kHz
    .FRACW( 15), .FRACN(44), .FRACM(13125)
) u_rcmix(
`ifdef JTFRAME_CLK48
    .rst    ( rst48     ),
    .clk    ( clk48     ),
`else
    .rst    ( rst       ),
    .clk    ( clk       ),
`endif
    .mute   ( mute      ),
    .sample ( sample    ),
    .ch_en  ( snd_en    ),
    .gpole  ( 15'h3F66 ),  // 19894 Hz 
    .ch0    ( { fm_l,fm_r } ),
    .ch1    ( 16'd0 ),
    .ch2    ( 16'd0 ),
    .ch3    ( 16'd0 ),
    .ch4    ( 16'd0 ),
    .ch5    ( 16'd0 ),
    .p0     ( 30'h0), // 0 Hz, 0 Hz 
    .p1     ( 30'h0), 
    .p2     ( 30'h0), 
    .p3     ( 30'h0), 
    .p4     ( 30'h0), 
    .p5     ( 30'h0), 
    .g0     ( 8'h80 ), // 1.00  fm
    .g1     ( 8'h00 ), // 0.00 
    .g2     ( 8'h00 ), // 0.00 
    .g3     ( 8'h00 ), // 0.00 
    .g4     ( 8'h00 ), // 0.00 
    .g5     ( 8'h00 ), // 0.00 
    .gain   ( snd_vol   ),
    .mixed  ( snd       ),
    .peak   ( snd_peak  ),
    .vu     ( snd_vu    )
);
`else
assign snd=0;
assign snd_vu   = 0;
assign snd_peak = 0;
wire ncs;
jtframe_frac_cen #(.WC(15)) u_cen192(
    .clk    ( clk       ),
    .n      ( 44 ),
    .m      ( 13125 ),
    .cen    ( {  ncs,sample }  ), // sample is always 192 kHz
    .cenb   (                  )
);
`endif
endmodule
