# Remember to update JTFRAME_SKIP when adding
# or removing betas
ngpc:     [ mister, pocket ]
riders:   [ mister, pocket ]
thundr:   [ mister, pocket ]
rungun:   [ mister, pocket ]
cal50:    [ mister, pocket ]
prmr:     [ mister, pocket ]
