# Remember to update JTFRAME_SKIP when adding
# or removing betas
ngpc:     [ mister, pocket ]
riders:   [ mister, pocket ]
thundr:   [ mister, pocket ]
paclan:   [ mister, pocket ]
rungun:   [ mister, pocket ]
