[global]
author=["jotego"]

[parse]
sourcefile=[ "segaorun.cpp" ]
skip.machines=["shangon"]
skip.bootlegs=true

[buttons]
Names = [
    { machine="outrun",  names="Accelerate,Brake,Gear (Low / High)"},
    { machine="toutrun", names="Accelerate,Brake,Gear (Low / High),Nitro"},
    { machine="shangon", names="Accelerate,Brake,-,Supercharger"},
]

[Audio]
volume = [
    { machine="outrun", value=0xEC },
    { machine="toutrun", value=0xA9 },
]

[dipsw]
delete=[{names=["Unused","Unknown","Credits"]}]
bitcnt = 16

[header]
fill=0
data = [
    { dev="fd1089a",     offset=0, data="02" },
    { dev="fd1089b",     offset=0, data="03" },
    { dev="fd1094",      offset=0, data="04" },
    { machine="shangon", offset=1, data="01" },
    { machine="toutrun", offset=1, data="02" }
]


[ROM]
regions = [
    { name="maincpu",     width=16, reverse=true },
    { name="subcpu",      start="JTFRAME_BA1_START", width=16, reverse=true },
    { name="soundcpu",    start="SND_START" },
    { name="pcm",         start="PCM_START", No_offset=true, Rom_len=0x10000 },
    { name="gfx1",        start="JTFRAME_BA2_START", width=32, sequence=[0,2,4,4, 1,3,5,5 ] },
    { name="gfx1",        start="JTFRAME_BA2_START", width=32, sequence=[0,1,2,2 ], No_offset=true, machine="toutrun" },
    { name="sprites",     start="JTFRAME_BA3_START", width=32, No_offset=true },
    { machine="shangon",  name="sprites",     start="JTFRAME_BA3_START", width=16, reverse=true }, # S16B sprites
    { name="segaic16road",start="ROAD_START", width=16, No_offset=true, singleton=true },
    { name="maincpu:key", start="JTFRAME_PROM_START", len=0x2000 },
    { name="fd1089",      start="FD1089_START" },
]

order = [
    "maincpu", "subcpu", "soundcpu", "pcm", "gfx1",
    "sprites", "segaic16road", "maincpu:key"
]
