/*  This file is part of JTCORES.
    JTCORES program is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    JTCORES program is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with JTCORES.  If not, see <http://www.gnu.org/licenses/>.

    Author: aCORES
    Version: 1.0
    Date: 18-8-2026 */

// Post-mix two-pole audio filter (AC-coupling HP + speaker-rolloff LP).
// Ported from the standalone MiSTer Universal_DoCastle core this core
// derives from.
//
// Audio-rate sourcing: the original board derives the audio rate as
// 49.152 MHz / 1024. Under jtframe's 48.000 MHz base that same divider gives
// 46.875 kHz, which also detunes both Q16 pole coefficients below. The local
// divider is therefore replaced by a `cen_48k` input port, generated by
// cfg/mem.yaml's clocks: block as an exact 48,000,000/1000 = 48,000 Hz clock
// enable (same mechanism as cen_mclk/cen_cpu).
//
// Why this stays a hand-written post-mix module rather than folding into
// mem.yaml's generated audio path:
//
//   1. mem.yaml's per-channel/global `rc:` filter mechanism is documented
//      (jtframe-mem.md "Audio Connections") as taking REAL schematic
//      resistor/capacitor component values (e.g. `rc: [{r: 1k, c: 33n}]`)
//      and computing the pole coefficients FROM them. This project has no
//      such schematic measurement for docastle's output stage: no real audio
//      RC/rsum values have been captured from the board, so there are no
//      stated component values to carry over. This file's two IIR poles
//      (the ~1.5 Hz HP/
//      AC-coupling pole at Q16 coefficient 65523/65536, and the ~12 kHz LP
//      speaker-rolloff pole at Q16 coefficient 51911/65536) are *already-
//      computed* magic coefficients with no backing R/C pair on record.
//      Reverse-engineering fake R/C values that happen to produce these
//      same coefficients just to satisfy the generator's input shape would
//      be fabricating schematic evidence that does not exist. If real
//      component values are ever measured from the 8302 audio board, then
//      re-deriving this as generator-driven `rc:` entries becomes the correct
//      simplification; not before.
//   2. Structurally, this module runs on the ALREADY-SUMMED 16-bit post-mix
//      signal (`sample_in`) as a single two-stage cascade (HP then LP) with
//      one shared `enable`/`reset`. jtframe's documented generator pieces
//      don't obviously match that shape: `dcrm` (jtframe_dcrm, the closest
//      analogue to the HP/AC-coupling stage -- "IIR filter to remove the DC
//      value of a signal") is documented as a PER-CHANNEL key in the
//      `channels:` list, not a post-mix stage; the LP `rc:` pole mechanism
//      is documented per-channel or as a single top-level `audio.rc` pole,
//      not as a second stage chained after a `dcrm`-style DC-removal stage.
//      Nothing in jtframe-mem.md's schema shows a documented "channel dcrm
//      + top-level rc in series" combination equivalent to what this module
//      does in one block.
//   3. Net effect: even setting aside the missing R/C provenance from point
//      1, the generator's documented building blocks don't cleanly express
//      this specific two-pole post-mix cascade as one generated stage today.
//
// So this module stays hand-written and is a genuine post-mix stage in the
// jtdocastle_game.v audio chain (after channel summing), not something the
// mem.yaml `audio:` section can currently subsume. Re-open this only if real
// 8302 board R/C measurements turn up, at which point genuine `rc:`/`dcrm:`
// entries become the correct simplification.
//
// PCB reference: the 8302 audio schematic -- four equal 1.5k PSG feeds
// already summed upstream; this stage models the AC-coupled MB3730 path at
// 48 kHz.
module jtdocastle_audio_filter
(
	input clk, input reset, input enable,
	// Generated by cfg/mem.yaml's clocks: block (48,000,000/1000 = 48,000
	// exactly), same jtframe_gated_cen mechanism as cen_mclk/cen_cpu.
	// Replaces a local /1024 divider -- see the header note.
	input cen_48k,
	input signed [15:0] sample_in,
	output signed [15:0] sample_out
);

wire ce_audio = cen_48k;
reg signed [31:0] x_prev, hp_state, lp_state;
reg signed [15:0] result;
wire signed [31:0] x_extended = {{16{sample_in[15]}},sample_in};
reg [2:0] filter_step;
reg signed [31:0] hp_delta_pipe, hp_next_pipe, lp_delta_pipe, lp_next_pipe;
reg signed [63:0] hp_product_pipe, lp_product_pipe;

always @(posedge clk) begin
	if (reset) begin
		filter_step <= 0;
		x_prev <= 0; hp_state <= 0; lp_state <= 0; result <= 0;
		hp_delta_pipe <= 0; hp_product_pipe <= 0; hp_next_pipe <= 0;
		lp_delta_pipe <= 0; lp_product_pipe <= 0; lp_next_pipe <= 0;
	end else begin
		// The complete IIR update still occurs once per 48 kHz sample.  Breaking
		// its two multiplies and clamp into short stages avoids a false need for
		// all of that arithmetic to settle in one 49.152 MHz clock period.
		if (ce_audio && filter_step == 0) begin
			x_prev <= x_extended;
			hp_delta_pipe <= x_extended - x_prev;
			hp_product_pipe <= hp_state * 32'sd65523; // 1.5 Hz HP pole, Q16
			filter_step <= 1;
		end else begin
			case (filter_step)
			3'd1: begin
				hp_next_pipe <= hp_delta_pipe + $signed(hp_product_pipe[47:16]);
				filter_step <= 2;
			end
			3'd2: begin
				lp_delta_pipe <= hp_next_pipe - lp_state;
				filter_step <= 3;
			end
			3'd3: begin
				lp_product_pipe <= lp_delta_pipe * 32'sd51911; // about 12 kHz LP, Q16
				filter_step <= 4;
			end
			3'd4: begin
				lp_next_pipe <= lp_state + $signed(lp_product_pipe[47:16]);
				hp_state <= hp_next_pipe;
				filter_step <= 5;
			end
			3'd5: begin
				lp_state <= lp_next_pipe;
				if (lp_next_pipe > 32'sd32767) result <= 16'sh7fff;
				else if (lp_next_pipe < -32'sd32768) result <= -16'sd32768;
				else result <= lp_next_pipe[15:0];
				filter_step <= 0;
			end
			default: filter_step <= 0;
			endcase
		end
	end
end
assign sample_out = enable ? result : sample_in;
endmodule
