// jtnnjema_game_sdram.v is automatically generated by JTFRAME
// Do not modify it
// Do not add it to git

`ifndef JTFRAME_COLORW
`define JTFRAME_COLORW 4
`endif

`ifndef JTFRAME_BUTTONS
`define JTFRAME_BUTTONS 2
`endif

module jtnnjema_game_sdram(
    `include "jtframe_common_ports.inc"
    `include "jtframe_mem_ports.inc"
);

/* verilator lint_off WIDTH */
localparam [25:0] BA1_START  =`ifdef JTFRAME_BA1_START  `JTFRAME_BA1_START  `else 26'd0 `endif;
localparam [25:0] BA2_START  =`ifdef JTFRAME_BA2_START  `JTFRAME_BA2_START  `else 26'd0 `endif;
localparam [25:0] BA3_START  =`ifdef JTFRAME_BA3_START  `JTFRAME_BA3_START  `else 26'd0 `endif;
localparam [25:0] PROM_START =`ifdef JTFRAME_PROM_START `JTFRAME_PROM_START `else 26'd0 `endif;
localparam [25:0] HEADER_LEN =`ifdef JTFRAME_HEADER     `JTFRAME_HEADER     `else 26'd0 `endif;
localparam        SDRAMW     =`ifdef JTFRAME_SDRAM_XL 25 `elsif JTFRAME_SDRAM_LARGE 24 `else 23 `endif;
localparam        IOCTL_AW   =`ifdef JTFRAME_SDRAM_XL 27 `else 26 `endif;
/* verilator lint_on WIDTH */


parameter BGMAP_OFFSET = (`BGMAP_START)>>1;
parameter SCR_OFFSET = (`SCR_START-`JTFRAME_BA2_START)>>1;
/* verilator tracing_off */
wire [7:0] ioctl_aux;
`ifndef JTFRAME_IOCTL_RD
    assign ioctl_aux=0;
`endif
wire [8-1:0] vcode_dimx;
wire [0:0] vcode_wemx;
wire [10-1:0] vcode_amux;
wire [8-1:0] vattr_dimx;
wire [0:0] vattr_wemx;
wire [10-1:0] vattr_amux;
wire [8-1:0] oram_dimx;
wire [0:0] oram_wemx;
wire [9-1:0] oram_amux;

// Audio channels 
wire signed [15:0] fm;
wire [ 7:0] dac1;
wire [ 7:0] dac2;
wire mute;
// Additional ports
wire [7:0] vcode_dout;
wire  vcwr_we;
wire [7:0] vawr_din;
wire [13:0] m4rom_addr;
wire [3:0] blue_data;
wire [9:0] vawr_addr;
wire [7:0] oram_dout;
wire [7:0] red_addr;
wire [7:0] ocpu_din;
wire [3:0] objbank_data;
wire [9:0] vattr_scan;
wire [7:0] vattr_dout;
wire [7:0] ocpu_dout;
wire [7:0] green_addr;
wire  vawr_we;
wire [7:0] vawr_dout;
wire [3:0] green_data;
wire [7:0] objbank_addr;
wire [7:0] vcwr_din;
wire [8:0] odma_addr;
wire [7:0] m4rom_data;
wire [3:0] red_data;
wire [7:0] objlut_addr;
wire [3:0] objlut_data;
wire [9:0] vcode_scan;
wire [9:0] vcwr_addr;
wire [7:0] vcwr_dout;
wire [8:0] ocpu_addr;
wire  ocpu_we;
wire [7:0] blue_addr;

// BRAM buses












// SDRAM buses

wire [16:0] main_addr;
wire [ 7:0] main_data;
wire        main_cs, main_ok;
wire [14:1] bgmap_addr;
wire [15:0] bgmap_data;
wire        bgmap_cs, bgmap_ok;
wire [15:0] snd_addr;
wire [ 7:0] snd_data;
wire        snd_cs, snd_ok;
wire [14:2] char_addr;
wire [31:0] char_data;
wire        char_cs, char_ok;
wire [16:2] scr_addr;
wire [31:0] scr_data;
wire        scr_cs, scr_ok;
wire [16:2] obj_addr;
wire [31:0] obj_data;
wire        obj_cs, obj_ok;
wire        prom_we, header;
wire [SDRAMW-2:0] raw_addr, post_addr;
wire [SDRAMW-2:0] ioctl_prog_addr   = ioctl_addr[SDRAMW-2:0];
wire [IOCTL_AW-1:0] pre_addr, dwnld_addr, ioctl_addr_noheader;
wire [ 7:0] post_data;
wire [15:0] raw_data;
wire [ 7:0] pcb_id;
wire        pass_io;
// Clock enable signals
wire cen12; 
wire cen6; 
wire cen4; 
wire cen2; 
wire gfx4_en, gfx8_en, gfx16_en, gfx16b_en, gfx16c_en, ioctl_dwn;

assign pass_io = header | ioctl_ram;
assign ioctl_addr_noheader = `ifdef JTFRAME_HEADER header ? ioctl_addr : ioctl_addr - HEADER_LEN `else ioctl_addr `endif ;
`ifdef JTFRAME_SDRAM_CACHE
assign burst_addr = { (SDRAMW-1){1'b0} };
assign burst_ba   = 2'd0;
assign burst_rd   = 1'b0;
assign burst_wr   = 1'b0;
assign burst_din  = 16'd0;
`endif

wire rst_h, rst24_h, rst48_h, hold_rst;

/* verilator tracing_off */
jtframe_rsthold u_hold(
    .rst    ( rst       ),
    .clk    ( clk       ),
    .hold   ( hold_rst  ),
    .rst_h  ( rst_h     ),
    .rst24  ( rst24     ),
    .clk24  ( clk24     ),
    .rst24_h( rst24_h   )
`ifdef JTFRAME_CLK48 ,
    .rst48  ( rst48     ),
    .clk48  ( clk48     ),
    .rst48_h( rst48_h   )
`endif
);
/* verilator tracing_on */
jtnnjema_game u_game(
    .rst        ( rst_h     ),
    .clk        ( clk       ),
    .rst24      ( rst24_h   ),
    .clk24      ( clk24     ),
`ifdef JTFRAME_CLK48
    .rst48      ( rst48_h   ),
    .clk48      ( clk48     ),
`endif
    .rst96      ( rst96     ),
    .clk96      ( clk96     ),
    // Audio channels
    .fm     ( fm      ),.dac1     ( dac1      ),.dac2     ( dac2      ),
    
    .snd_en         ( snd_en        ),
    .snd_vol        ( snd_vol       ),
    .cen12    ( cen12    ), 
    .cen6    ( cen6    ), 
    .cen4    ( cen4    ), 
    .cen2    ( cen2    ), 

    .pxl2_cen       ( pxl2_cen      ),
    .pxl_cen        ( pxl_cen       ),
    .red            ( red           ),
    .green          ( green         ),
    .blue           ( blue          ),
    .LHBL           ( LHBL          ),
    .LVBL           ( LVBL          ),
    .HS             ( HS            ),
    .VS             ( VS            ),
    // cabinet I/O
    .cab_1p   ( cab_1p  ),
    .coin     ( coin    ),
    .joystick1    ( joystick1        ), .joystick2    ( joystick2        ),
    .joystick3    ( joystick3        ), .joystick4    ( joystick4        ), `ifdef JTFRAME_MOUSE
    .mouse_1p     ( mouse_1p         ), .mouse_2p     ( mouse_2p         ), .mouse_strobe ( mouse_strobe ), `endif `ifdef JTFRAME_LIGHTGUN
    .gun_1p_x     ( gun_1p_x         ), .gun_1p_y     ( gun_1p_y         ),
    .gun_2p_x     ( gun_2p_x         ), .gun_2p_y     ( gun_2p_y         ), `endif `ifdef JTFRAME_SPINNER
    .spinner_1p   ( spinner_1p       ), .spinner_2p   ( spinner_2p       ), `endif
    .joyana_l1    ( joyana_l1        ), .joyana_l2    ( joyana_l2        ),
    .joyana_l3    ( joyana_l3        ), .joyana_l4    ( joyana_l4        ),
    .joyana_r1    ( joyana_r1        ), .joyana_r2    ( joyana_r2        ),
    .joyana_r3    ( joyana_r3        ), .joyana_r4    ( joyana_r4        ),
    .dial_x       ( dial_x           ), .dial_y       ( dial_y           ),
    // DIP switches
    .status         ( status        ),
    .dipsw          ( dipsw         ),
    .service        ( service       ),
    .tilt           ( tilt          ),
    .dip_pause      ( dip_pause     ),
    .dip_flip       ( dip_flip      ),
    .dip_test       ( dip_test      ),
    .dip_fxlevel    ( dip_fxlevel   ),
    // Ports declared in mem.yaml
    .vcode_dout   ( vcode_dout ),
    .vcwr_we   ( vcwr_we ),
    .vawr_din   ( vawr_din ),
    .m4rom_addr   ( m4rom_addr ),
    .blue_data   ( blue_data ),
    .vawr_addr   ( vawr_addr ),
    .oram_dout   ( oram_dout ),
    .red_addr   ( red_addr ),
    .ocpu_din   ( ocpu_din ),
    .objbank_data   ( objbank_data ),
    .vattr_scan   ( vattr_scan ),
    .vattr_dout   ( vattr_dout ),
    .ocpu_dout   ( ocpu_dout ),
    .green_addr   ( green_addr ),
    .vawr_we   ( vawr_we ),
    .vawr_dout   ( vawr_dout ),
    .green_data   ( green_data ),
    .objbank_addr   ( objbank_addr ),
    .vcwr_din   ( vcwr_din ),
    .odma_addr   ( odma_addr ),
    .m4rom_data   ( m4rom_data ),
    .red_data   ( red_data ),
    .objlut_addr   ( objlut_addr ),
    .objlut_data   ( objlut_data ),
    .vcode_scan   ( vcode_scan ),
    .vcwr_addr   ( vcwr_addr ),
    .vcwr_dout   ( vcwr_dout ),
    .ocpu_addr   ( ocpu_addr ),
    .ocpu_we   ( ocpu_we ),
    .blue_addr   ( blue_addr ),
    // Memory interface - SDRAM
    .main_addr ( main_addr ),
    .main_cs   ( main_cs   ),
    .main_ok   ( main_ok   ),
    .main_data ( main_data ),
    
    .bgmap_addr ( bgmap_addr ),
    .bgmap_cs   ( bgmap_cs   ),
    .bgmap_ok   ( bgmap_ok   ),
    .bgmap_data ( bgmap_data ),
    
    .snd_addr ( snd_addr ),
    .snd_cs   ( snd_cs   ),
    .snd_ok   ( snd_ok   ),
    .snd_data ( snd_data ),
    
    .char_addr ( char_addr ),
    .char_cs   ( char_cs   ),
    .char_ok   ( char_ok   ),
    .char_data ( char_data ),
    
    .scr_addr ( scr_addr ),
    .scr_cs   ( scr_cs   ),
    .scr_ok   ( scr_ok   ),
    .scr_data ( scr_data ),
    
    .obj_addr ( obj_addr ),
    .obj_cs   ( obj_cs   ),
    .obj_ok   ( obj_ok   ),
    .obj_data ( obj_data ),
    
    // Memory interface - BRAM

    
    
    
    
    
    
`ifdef JTFRAME_SRAM
    // SRAM
    .sram_addr  ( sram_addr     ),
    .sram_din   ( sram_din      ),
    .sram_dout  ( sram_dout     ),
    .sram_wen   ( sram_wen      ),
    .sram_dsn   ( sram_dsn      ),
    .sram_ok    ( sram_ok       ),
`endif

`ifdef JTFRAME_SAVEGAME
    // Save/Load
    .sav_change ( sav_change    ),
    .sav_wait   ( sav_wait      ),
    .sav_done   ( sav_done      ),
    .sav_wr     ( sav_wr        ),
    .sav_ack    ( sav_ack       ),
    .sav_din    ( sav_din       ),
    .sav_dout   ( sav_dout      ),
    .sav_addr   ( sav_addr      ),
`endif
    // PROM writting
    .ioctl_addr   ( pass_io ? ioctl_addr       : ioctl_addr_noheader  ),
    .prog_addr    ( pass_io ? ioctl_prog_addr : raw_addr      ),
    .prog_data    ( pass_io ? ioctl_dout       : raw_data[7:0] ),
    .prog_we      ( pass_io ? ioctl_wr         : prog_we       ),
    .prog_ba      ( prog_ba        ), // prog_ba supplied in case it helps re-mapping addresses
    .prom_we      ( pass_io ? 1'b0 : prom_we ),
`ifdef JTFRAME_HEADER
    .header       ( header         ),
`endif
`ifdef JTFRAME_IOCTL_RD
    .ioctl_din    ( ioctl_aux      ),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ), `endif
    .ioctl_ram    ( ioctl_ram      ),
    .ioctl_cart   ( ioctl_cart     ),
    // Debug
    .debug_bus    ( debug_bus      ),
    .debug_view   ( debug_view     ),
`ifdef JTFRAME_STATUS
    .st_addr      ( st_addr        ),
    .st_dout      ( st_dout        ),
`endif
`ifdef JTFRAME_LF_BUFFER
    .game_vrender( game_vrender  ),
    .game_hdump  ( game_hdump    ),
    .ln_addr     ( ln_addr       ),
    .ln_data     ( ln_data       ),
    .ln_done     ( ln_done       ),
    .ln_hs       ( ln_hs         ),
    .ln_dout     ( ln_dout       ),
    .ln_pxl      ( ln_pxl        ),
    .ln_v        ( ln_v          ),
    .ln_vs       ( ln_vs         ),
    .ln_lvbl     ( ln_lvbl       ),
    .ln_we       ( ln_we         ),
    .fb_keep     ( fb_keep       ),
`ifdef JTFRAME_LF_ZOOM
    .h_step      ( h_step        ),
    .v_step      ( v_step        ),
`endif
`endif
    .gfx_en      ( gfx_en        )
);
/* verilator tracing_off */
assign dwnld_busy = ioctl_rom | prom_we | prog_we; // prom_we is really just for sims
assign dwnld_addr = ioctl_addr;
`ifdef JTFRAME_SDRAM_XL
wire [26:0] dwnld_addr_wide = dwnld_addr;
`else
wire [26:0] dwnld_addr_wide = {1'b0,dwnld_addr};
`endif
assign prog_addr = raw_addr;
assign prog_data = raw_data;
assign gfx4_en   = 0;
assign gfx8_en   = 0;
assign gfx16_en  = 0;
assign gfx16b_en = 0;
assign gfx16c_en = 0;
assign ioctl_dwn = ioctl_rom | ioctl_cart;
`ifdef VERILATOR_KEEP_SDRAM /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_dwnld #(
    .SDRAMW     ( SDRAMW       ),
`ifdef JTFRAME_HEADER
    .HEADER    ( `JTFRAME_HEADER   ),
`endif
`ifdef JTFRAME_BA1_START
    .BA1_START ( BA1_START ),
`endif
`ifdef JTFRAME_BA2_START
    .BA2_START ( BA2_START ),
`endif
`ifdef JTFRAME_BA3_START
    .BA3_START ( BA3_START ),
`endif
`ifdef JTFRAME_PROM_START
    .PROM_START( PROM_START ),
`endif
    .SWAB      ( 1),
    .GFX8B0    ( 0),
    .GFX16B0   ( 0)
) u_dwnld(
    .clk          ( clk            ),
    .ioctl_rom    ( ioctl_dwn      ),
    .ioctl_addr   ( dwnld_addr_wide),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .gfx4_en      ( gfx4_en        ),
    .gfx8_en      ( gfx8_en        ),
    .gfx16_en     ( gfx16_en       ),
    .gfx16b_en    ( gfx16b_en      ),
    .gfx16c_en    ( gfx16c_en      ),
    .prog_addr    ( raw_addr       ),
    .prog_data    ( raw_data       ),
    .prog_mask    ( prog_mask      ), // active low
    .prog_we      ( prog_we        ),
    .prog_rd      ( prog_rd        ),
    .prog_ba      ( prog_ba        ),
    .prom_we      ( prom_we        ),
    .header       ( header         ),
    .sdram_ack    ( prog_ack       )
);

jtframe_headerbyte #(.AW(6)) u_pcbid(
    .clk          ( clk            ),
    .header       ( header         ),
    .ioctl_addr   ( ioctl_addr[5:0]),
    .ioctl_dout   ( ioctl_dout     ),
    .ioctl_wr     ( ioctl_wr       ),
    .dout         ( pcb_id         )
);
`ifdef VERILATOR_KEEP_SDRAM /* verilator tracing_on */ `else /* verilator tracing_off */ `endif


jtframe_rom_2slots #(
    .SDRAMW(SDRAMW-1),
    .TAG_RAM(0),
    // main
    .SLOT0_AW(17),
    .SLOT0_DW( 8), 
    // bgmap
    .SLOT1_OFFSET(BGMAP_OFFSET[SDRAMW-2:0]),
    .SLOT1_AW(14),
    .SLOT1_DW(16)
`ifdef JTFRAME_BA0_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
`endif
`ifdef JTFRAME_BA0_LEN
    ,.SLOT0_BURSTLEN(`JTFRAME_BA0_LEN)
`else
    ,.SLOT0_BURSTLEN(32)
`endif
`ifdef JTFRAME_BA0_LEN
    ,.SLOT1_BURSTLEN(`JTFRAME_BA0_LEN)
`else
    ,.SLOT1_BURSTLEN(32)
`endif
) u_bank0(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( main_addr  ),
    .slot0_dout  ( main_data  ),
    .slot0_cs    ( main_cs    ),
    .slot0_ok    ( main_ok    ),
    
    .slot1_addr  ( bgmap_addr  ),
    .slot1_dout  ( bgmap_data  ),
    .slot1_cs    ( bgmap_cs    ),
    .slot1_ok    ( bgmap_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[0]  ),
    .sdram_rd    ( ba_rd[0]   ),
    .sdram_addr  ( ba0_addr   ),
    .data_dst    ( ba_dst[0]  ),
    .data_rdy    ( ba_rdy[0]  ),
    .data_read   ( data_read  )
);
assign ba_wr[0] = 0;
assign ba0_din  = 0;
assign ba0_dsn  = 3;
jtframe_rom_1slot #(
    .SDRAMW(SDRAMW-1),
    .TAG_RAM(0),
    // snd
    .SLOT0_AW(16),
    .SLOT0_DW( 8)
`ifdef JTFRAME_BA1_LEN
    ,.SLOT0_DOUBLE(1)
`endif
`ifdef JTFRAME_BA1_LEN
    ,.SLOT0_BURSTLEN(`JTFRAME_BA1_LEN)
`else
    ,.SLOT0_BURSTLEN(32)
`endif
) u_bank1(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( snd_addr  ),
    .slot0_dout  ( snd_data  ),
    .slot0_cs    ( snd_cs    ),
    .slot0_ok    ( snd_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[1]  ),
    .sdram_rd    ( ba_rd[1]   ),
    .sdram_addr  ( ba1_addr   ),
    .data_dst    ( ba_dst[1]  ),
    .data_rdy    ( ba_rdy[1]  ),
    .data_read   ( data_read  )
);
assign ba_wr[1] = 0;
assign ba1_din  = 0;
assign ba1_dsn  = 3;
jtframe_rom_2slots #(
    .SDRAMW(SDRAMW-1),
    .TAG_RAM(0),
    // char
    .SLOT0_AW(14),
    .SLOT0_DW(32), 
    // scr
    .SLOT1_OFFSET(SCR_OFFSET[SDRAMW-2:0]),
    .SLOT1_AW(16),
    .SLOT1_DW(32)
`ifdef JTFRAME_BA2_LEN
    ,.SLOT0_DOUBLE(1)
    ,.SLOT1_DOUBLE(1)
`endif
`ifdef JTFRAME_BA2_LEN
    ,.SLOT0_BURSTLEN(`JTFRAME_BA2_LEN)
`else
    ,.SLOT0_BURSTLEN(32)
`endif
`ifdef JTFRAME_BA2_LEN
    ,.SLOT1_BURSTLEN(`JTFRAME_BA2_LEN)
`else
    ,.SLOT1_BURSTLEN(32)
`endif
) u_bank2(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( { char_addr, 1'b0 } ),
    .slot0_dout  ( char_data  ),
    .slot0_cs    ( char_cs    ),
    .slot0_ok    ( char_ok    ),
    
    .slot1_addr  ( { scr_addr, 1'b0 } ),
    .slot1_dout  ( scr_data  ),
    .slot1_cs    ( scr_cs    ),
    .slot1_ok    ( scr_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[2]  ),
    .sdram_rd    ( ba_rd[2]   ),
    .sdram_addr  ( ba2_addr   ),
    .data_dst    ( ba_dst[2]  ),
    .data_rdy    ( ba_rdy[2]  ),
    .data_read   ( data_read  )
);
assign ba_wr[2] = 0;
assign ba2_din  = 0;
assign ba2_dsn  = 3;
jtframe_rom_1slot #(
    .SDRAMW(SDRAMW-1),
    .TAG_RAM(0),
    // obj
    .SLOT0_AW(16),
    .SLOT0_DW(32)
`ifdef JTFRAME_BA3_LEN
    ,.SLOT0_DOUBLE(1)
`endif
`ifdef JTFRAME_BA3_LEN
    ,.SLOT0_BURSTLEN(`JTFRAME_BA3_LEN)
`else
    ,.SLOT0_BURSTLEN(32)
`endif
) u_bank3(
    .rst         ( rst        ),
    .clk         ( clk        ),
    
    .slot0_addr  ( { obj_addr, 1'b0 } ),
    .slot0_dout  ( obj_data  ),
    .slot0_cs    ( obj_cs    ),
    .slot0_ok    ( obj_ok    ),
    
    // SDRAM controller interface
    .sdram_ack   ( ba_ack[3]  ),
    .sdram_rd    ( ba_rd[3]   ),
    .sdram_addr  ( ba3_addr   ),
    .data_dst    ( ba_dst[3]  ),
    .data_rdy    ( ba_rdy[3]  ),
    .data_read   ( data_read  )
);
assign ba_wr[3] = 0;
assign ba3_din  = 0;
assign ba3_dsn  = 3;
assign hold_rst=0;
`ifdef JTFRAME_PROM_START
localparam JTFRAME_PROM_START=`JTFRAME_PROM_START;
`endif

// Dual port BRAM for vcode and vcwr
jtframe_dual_ram #(
    .AW(10),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .SIMFILE("vcode.bin")
) u_bram_vcode(
    // Port 0 - vcode
    .clk0   ( clk ),
    .addr0  ( vcode_amux ),
    .data0  ( 8'h0 ),
    .we0    ( 1'd0 ),
    .q0     ( vcode_dout ),
    // Port 1 - vcwr
    .clk1   ( clk ),
    .data1  ( vcwr_din ),
    .addr1  ( vcwr_addr[9:0] ),
    .we1    ( vcwr_we  ),
    .q1     ( vcwr_dout )
);
// Dual port BRAM for vattr and vawr
jtframe_dual_ram #(
    .AW(10),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .SIMFILE("vattr.bin")
) u_bram_vattr(
    // Port 0 - vattr
    .clk0   ( clk ),
    .addr0  ( vattr_amux ),
    .data0  ( 8'h0 ),
    .we0    ( 1'd0 ),
    .q0     ( vattr_dout ),
    // Port 1 - vawr
    .clk1   ( clk ),
    .data1  ( vawr_din ),
    .addr1  ( vawr_addr[9:0] ),
    .we1    ( vawr_we  ),
    .q1     ( vawr_dout )
);
// Dual port BRAM for oram and ocpu
jtframe_dual_ram #(
    .AW(9),
    .LATCH0_IN(0),
    .LATCH0_OUT(0),
    .LATCH1_IN(0),
    .LATCH1_OUT(0),
    .SIMFILE("oram.bin")
) u_bram_oram(
    // Port 0 - oram
    .clk0   ( clk ),
    .addr0  ( oram_amux ),
    .data0  ( 8'h0 ),
    .we0    ( 1'd0 ),
    .q0     ( oram_dout ),
    // Port 1 - ocpu
    .clk1   ( clk ),
    .data1  ( ocpu_din ),
    .addr1  ( ocpu_addr[8:0] ),
    .we1    ( ocpu_we  ),
    .q1     ( ocpu_dout )
);// m4rom PROM
wire [ 7:0]m4rom_dd;
wire [13:0]m4rom_waddr;
wire       m4rom_we;

jtframe_ioctl_range #(
    .AW(14),
    .OFFSET(JTFRAME_PROM_START+'h0)
) u_range_m4rom(
    .clk        ( clk                ),
    .addr       ( raw_addr           ),
    .addr_rel   ( m4rom_waddr        ),
    .en         ( prom_we            ),
    .inrange    ( m4rom_we           ),
    .din        ( raw_data[7:0]      ),
    .dout       ( m4rom_dd           )
);

jtframe_prom #(
    .DW(8),
    .AW(14)
) u_prom_m4rom(
    .clk        ( clk                ),
    .cen        ( 1'b1               ),
    .data       ( m4rom_dd[ 7:0]     ),
    .rd_addr    ( m4rom_addr         ),
    .wr_addr    ( m4rom_waddr        ),
    .we         ( m4rom_we           ),
    .q          ( m4rom_data         )
);
// red PROM
wire [ 7:0]red_dd;
wire [ 7:0]red_waddr;
wire       red_we;

jtframe_ioctl_range #(
    .AW(8),
    .OFFSET(JTFRAME_PROM_START+'h4000)
) u_range_red(
    .clk        ( clk                ),
    .addr       ( raw_addr           ),
    .addr_rel   ( red_waddr          ),
    .en         ( prom_we            ),
    .inrange    ( red_we             ),
    .din        ( raw_data[7:0]      ),
    .dout       ( red_dd             )
);

jtframe_prom #(
    .DW(4),
    .AW(8)
) u_prom_red(
    .clk        ( clk                ),
    .cen        ( 1'b1               ),
    .data       ( red_dd[ 3:0]       ),
    .rd_addr    ( red_addr           ),
    .wr_addr    ( red_waddr          ),
    .we         ( red_we             ),
    .q          ( red_data           )
);
// green PROM
wire [ 7:0]green_dd;
wire [ 7:0]green_waddr;
wire       green_we;

jtframe_ioctl_range #(
    .AW(8),
    .OFFSET(JTFRAME_PROM_START+'h4100)
) u_range_green(
    .clk        ( clk                ),
    .addr       ( raw_addr           ),
    .addr_rel   ( green_waddr        ),
    .en         ( prom_we            ),
    .inrange    ( green_we           ),
    .din        ( raw_data[7:0]      ),
    .dout       ( green_dd           )
);

jtframe_prom #(
    .DW(4),
    .AW(8)
) u_prom_green(
    .clk        ( clk                ),
    .cen        ( 1'b1               ),
    .data       ( green_dd[ 3:0]     ),
    .rd_addr    ( green_addr         ),
    .wr_addr    ( green_waddr        ),
    .we         ( green_we           ),
    .q          ( green_data         )
);
// blue PROM
wire [ 7:0]blue_dd;
wire [ 7:0]blue_waddr;
wire       blue_we;

jtframe_ioctl_range #(
    .AW(8),
    .OFFSET(JTFRAME_PROM_START+'h4200)
) u_range_blue(
    .clk        ( clk                ),
    .addr       ( raw_addr           ),
    .addr_rel   ( blue_waddr         ),
    .en         ( prom_we            ),
    .inrange    ( blue_we            ),
    .din        ( raw_data[7:0]      ),
    .dout       ( blue_dd            )
);

jtframe_prom #(
    .DW(4),
    .AW(8)
) u_prom_blue(
    .clk        ( clk                ),
    .cen        ( 1'b1               ),
    .data       ( blue_dd[ 3:0]      ),
    .rd_addr    ( blue_addr          ),
    .wr_addr    ( blue_waddr         ),
    .we         ( blue_we            ),
    .q          ( blue_data          )
);
// objlut PROM
wire [ 7:0]objlut_dd;
wire [ 7:0]objlut_waddr;
wire       objlut_we;

jtframe_ioctl_range #(
    .AW(8),
    .OFFSET(JTFRAME_PROM_START+'h4300)
) u_range_objlut(
    .clk        ( clk                ),
    .addr       ( raw_addr           ),
    .addr_rel   ( objlut_waddr       ),
    .en         ( prom_we            ),
    .inrange    ( objlut_we          ),
    .din        ( raw_data[7:0]      ),
    .dout       ( objlut_dd          )
);

jtframe_prom #(
    .DW(4),
    .AW(8)
) u_prom_objlut(
    .clk        ( clk                ),
    .cen        ( 1'b1               ),
    .data       ( objlut_dd[ 3:0]    ),
    .rd_addr    ( objlut_addr        ),
    .wr_addr    ( objlut_waddr       ),
    .we         ( objlut_we          ),
    .q          ( objlut_data        )
);
// objbank PROM
wire [ 7:0]objbank_dd;
wire [ 7:0]objbank_waddr;
wire       objbank_we;

jtframe_ioctl_range #(
    .AW(8),
    .OFFSET(JTFRAME_PROM_START+'h4400)
) u_range_objbank(
    .clk        ( clk                ),
    .addr       ( raw_addr           ),
    .addr_rel   ( objbank_waddr      ),
    .en         ( prom_we            ),
    .inrange    ( objbank_we         ),
    .din        ( raw_data[7:0]      ),
    .dout       ( objbank_dd         )
);

jtframe_prom #(
    .DW(4),
    .AW(8)
) u_prom_objbank(
    .clk        ( clk                ),
    .cen        ( 1'b1               ),
    .data       ( objbank_dd[ 3:0]   ),
    .rd_addr    ( objbank_addr       ),
    .wr_addr    ( objbank_waddr      ),
    .we         ( objbank_we         ),
    .q          ( objbank_data       )
);

`ifndef JTFRAME_SIM_IODUMP /* verilator tracing_off */ `endif
jtframe_ioctl_dump #(
    .DW0( 8 ), .AW0( 10 ),
    .DW1( 8 ), .AW1( 10 ),
    .DW2( 8 ), .AW2( 9 ),
    .DW3( 8 ), .AW3( 0 ),
    .DW4( 8 ), .AW4( 0 ),
    .DW5( 8 ), .AW5( 0 )
) u_dump (
    .clk       ( clk        ),
    // dump 0
    .dout0        ( vcode_dout ),
    .addr0        ( vcode_scan ),
    .addr0_mx     ( vcode_amux ),
    // restore
    .din0         ( 8'd0 ),
    .din0_mx      ( vcode_dimx ),
    .we0          ( 1'b0),
    .we0_mx       ( vcode_wemx ),
    
    // dump 1
    .dout1        ( vattr_dout ),
    .addr1        ( vattr_scan ),
    .addr1_mx     ( vattr_amux ),
    // restore
    .din1         ( 8'd0 ),
    .din1_mx      ( vattr_dimx ),
    .we1          ( 1'b0),
    .we1_mx       ( vattr_wemx ),
    
    // dump 2
    .dout2        ( oram_dout ),
    .addr2        ( odma_addr ),
    .addr2_mx     ( oram_amux ),
    // restore
    .din2         ( 8'd0 ),
    .din2_mx      ( oram_dimx ),
    .we2          ( 1'b0),
    .we2_mx       ( oram_wemx ),
    
    // dump 3
    .dout3        ( 8'd0 ),
    .addr3        ( 1'b0 ),
    .addr3_mx     (  ),
    // restore
    .din3         (  ),
    .din3_mx      (  ),
    .we3          ( 1'b0),
    .we3_mx       (  ),
    
    // dump 4
    .dout4        ( 8'd0 ),
    .addr4        ( 1'b0 ),
    .addr4_mx     (  ),
    // restore
    .din4         (  ),
    .din4_mx      (  ),
    .we4          ( 1'b0),
    .we4_mx       (  ),
    
    // dump 5
    .dout5        ( 8'd0 ),
    .addr5        ( 1'b0 ),
    .addr5_mx     (  ),
    // restore
    .din5         (  ),
    .din5_mx      (  ),
    .we5          ( 1'b0),
    .we5_mx       (  ),
    
    .ioctl_addr ( ioctl_addr[23:0] ),
    .ioctl_ram  ( ioctl_ram ),
    .ioctl_aux  ( ioctl_aux ),
    .ioctl_wr   ( ioctl_wr  ),
`ifdef JTFRAME_IOCTL_RD
    .ioctl_din  ( ioctl_din ),
`else
    .ioctl_din  (           ),
`endif
    .ioctl_dout ( ioctl_dout)
);




// Clock enable generation
// 12000000 = 48000000*1/4 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(2),.NUM(1),.DEN(4),.MFREQ(48000)) u_cen0_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( 1'b0    ),
    .cen    ( { cen6, cen12 } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

// 4000000 = 48000000*1/12 Hz from clk
`ifdef VERILATOR_KEEP_CEN /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
jtframe_gated_cen #(.W(2),.NUM(1),.DEN(12),.MFREQ(48000)) u_cen1_clk(
    .rst    ( rst          ),
    .clk    ( clk ),
    .busy   ( 1'b0    ),
    .cen    ( { cen2, cen4 } ),
    .fave   (              ),
    .fworst (              )
); /* verilator tracing_off */

`ifndef NOSOUND
`ifdef VERILATOR_KEEP_AUDIO /* verilator tracing_on */ `else /* verilator tracing_off */ `endif
assign mute=0;

jtframe_rcmix #(
    .W0(16),
    .W1(8),
    .W2(8),
    .STEREO0( 0),
    .STEREO1( 0),
    .STEREO2( 0),
    .STEREO3( 0),
    .STEREO4( 0),
    .STEREO5( 0),
    .DCRM0  ( 0),
    .DCRM1  ( 1),
    .DCRM2  ( 1),
    .DCRM3  ( 0),
    .DCRM4  ( 0),
    .DCRM5  ( 0),
    .STEREO ( 0),
    // Fractional cen for 192kHz
    .FRACW( 9), .FRACN(1), .FRACM(250)
) u_rcmix(
`ifdef JTFRAME_CLK48
    .rst    ( rst48     ),
    .clk    ( clk48     ),
`else
    .rst    ( rst       ),
    .clk    ( clk       ),
`endif
    .mute   ( mute      ),
    .sample ( sample    ),
    .ch_en  ( snd_en    ),
    .gpole  ( 15'h3F66 ),  // 19894 Hz 
    .ch0    ( fm ),
    .ch1    ( dac1 ),
    .ch2    ( dac2 ),
    .ch3    ( 16'd0 ),
    .ch4    ( 16'd0 ),
    .ch5    ( 16'd0 ),
    .p0     ( {15'h1E26,15'h5AE5}), // 10261 Hz, 33863 Hz 
    .p1     ( {15'h728B,15'h797F}), // 1592 Hz, 3386 Hz 
    .p2     ( {15'h728B,15'h797F}), // 1592 Hz, 3386 Hz 
    .p3     ( 30'h0), 
    .p4     ( 30'h0), 
    .p5     ( 30'h0), 
    .g0     ( 8'h80 ), // 1.00  fm
    .g1     ( 8'h50 ), // 0.62  dac1
    .g2     ( 8'h6F ), // 0.87  dac2
    .g3     ( 8'h00 ), // 0.00 
    .g4     ( 8'h00 ), // 0.00 
    .g5     ( 8'h00 ), // 0.00 
    .gain   ( snd_vol   ),
    .mixed  ( snd       ),
    .peak   ( snd_peak  ),
    .vu     ( snd_vu    )
);
`else
assign snd=0;
assign snd_vu   = 0;
assign snd_peak = 0;
wire ncs;
jtframe_frac_cen #(.WC(9)) u_cen192(
    .clk    ( clk       ),
    .n      ( 1 ),
    .m      ( 250 ),
    .cen    ( {  ncs,sample }  ), // sample is always 192 kHz
    .cenb   (                  )
);
`endif
endmodule
