[global]
author=["Fulvio Venturelli"]

[parse.machine]
name="gradius3"
sourcefile="konami/gradius3.cpp"
description="Gradius III (World, version R)"
year="1989"
manufacturer="Konami"

[parse.machine.display]
rotate=0
width=320
height=224

[parse.machine.sound]
channels=1

[parse.machine.input]
players=2
[[parse.machine.input.control]]
type="joy"
buttons=3
ways="8"

[[parse.machine.dipswitch]]
name="Coin A"
tag="DSW1"
mask=15
[[parse.machine.dipswitch.dipvalue]]
name="Free Play"
value=0
[[parse.machine.dipswitch.dipvalue]]
name="4 Coins/3 Credits"
value=1
[[parse.machine.dipswitch.dipvalue]]
name="4 Coins/1 Credit"
value=2
[[parse.machine.dipswitch.dipvalue]]
name="4 Coins/5 Credits"
value=3
[[parse.machine.dipswitch.dipvalue]]
name="3 Coins/2 Credits"
value=4
[[parse.machine.dipswitch.dipvalue]]
name="3 Coins/1 Credit"
value=5
[[parse.machine.dipswitch.dipvalue]]
name="2 Coins/5 Credits"
value=6
[[parse.machine.dipswitch.dipvalue]]
name="3 Coins/4 Credits"
value=7
[[parse.machine.dipswitch.dipvalue]]
name="2 Coins/1 Credit"
value=8
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/7 Credits"
value=9
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/6 Credits"
value=10
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/5 Credits"
value=11
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/4 Credits"
value=12
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/3 Credits"
value=13
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/2 Credits"
value=14
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/1 Credit"
value=15
default="yes"

[[parse.machine.dipswitch]]
name="Coin B"
tag="DSW1"
mask=240
[[parse.machine.dipswitch.dipvalue]]
name="Invalid"
value=0
[[parse.machine.dipswitch.dipvalue]]
name="4 Coins/3 Credits"
value=16
[[parse.machine.dipswitch.dipvalue]]
name="4 Coins/1 Credit"
value=32
[[parse.machine.dipswitch.dipvalue]]
name="4 Coins/5 Credits"
value=48
[[parse.machine.dipswitch.dipvalue]]
name="3 Coins/2 Credits"
value=64
[[parse.machine.dipswitch.dipvalue]]
name="3 Coins/1 Credit"
value=80
[[parse.machine.dipswitch.dipvalue]]
name="2 Coins/5 Credits"
value=96
[[parse.machine.dipswitch.dipvalue]]
name="3 Coins/4 Credits"
value=112
[[parse.machine.dipswitch.dipvalue]]
name="2 Coins/1 Credit"
value=128
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/7 Credits"
value=144
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/6 Credits"
value=160
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/5 Credits"
value=176
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/4 Credits"
value=192
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/3 Credits"
value=208
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/2 Credits"
value=224
[[parse.machine.dipswitch.dipvalue]]
name="1 Coin/1 Credit"
value=240
default="yes"

[[parse.machine.dipswitch]]
name="Lives"
tag="DSW2"
mask=3
[[parse.machine.dipswitch.dipvalue]]
name="7"
value=0
[[parse.machine.dipswitch.dipvalue]]
name="5"
value=1
[[parse.machine.dipswitch.dipvalue]]
name="3"
value=2
default="yes"
[[parse.machine.dipswitch.dipvalue]]
name="2"
value=3

[[parse.machine.dipswitch]]
name="Cabinet"
tag="DSW2"
mask=4
[[parse.machine.dipswitch.dipvalue]]
name="Upright"
value=0
default="yes"
[[parse.machine.dipswitch.dipvalue]]
name="Cocktail"
value=4

[[parse.machine.dipswitch]]
name="Bonus Life"
tag="DSW2"
mask=24
[[parse.machine.dipswitch.dipvalue]]
name="100k only"
value=0
[[parse.machine.dipswitch.dipvalue]]
name="50k only"
value=8
[[parse.machine.dipswitch.dipvalue]]
name="100k and every 100k"
value=16
[[parse.machine.dipswitch.dipvalue]]
name="20k and every 70k"
value=24
default="yes"

[[parse.machine.dipswitch]]
name="Difficulty"
tag="DSW2"
mask=96
[[parse.machine.dipswitch.dipvalue]]
name="Hardest"
value=0
[[parse.machine.dipswitch.dipvalue]]
name="Hard"
value=32
[[parse.machine.dipswitch.dipvalue]]
name="Normal"
value=64
default="yes"
[[parse.machine.dipswitch.dipvalue]]
name="Easy"
value=96

[[parse.machine.dipswitch]]
name="Demo Sounds"
tag="DSW2"
mask=128
[[parse.machine.dipswitch.dipvalue]]
name="On"
value=0
default="yes"
[[parse.machine.dipswitch.dipvalue]]
name="Off"
value=128

[[parse.machine.dipswitch]]
name="Flip Screen"
tag="DSW3"
mask=1
[[parse.machine.dipswitch.dipvalue]]
name="On"
value=0
[[parse.machine.dipswitch.dipvalue]]
name="Off"
value=1
default="yes"

[[parse.machine.dipswitch]]
name="Upright Controls"
tag="DSW3"
mask=2
[[parse.machine.dipswitch.dipvalue]]
name="Dual"
value=0
[[parse.machine.dipswitch.dipvalue]]
name="Single"
value=2
default="yes"

[[parse.machine.dipswitch]]
name="Service Mode"
tag="DSW3"
mask=4
[[parse.machine.dipswitch.dipvalue]]
name="On"
value=0
[[parse.machine.dipswitch.dipvalue]]
name="Off"
value=4
default="yes"

[[parse.machine.rom]]
name="945_r13.f15"
size=131072
crc="cffd103f"
region="maincpu"
offset=0x00000
[[parse.machine.rom]]
name="945_r12.e15"
size=131072
crc="0b968ef6"
region="maincpu"
offset=0x00001

[[parse.machine.rom]]
name="945_m09.r17"
size=131072
crc="b4a6df25"
region="sub"
offset=0x000000
[[parse.machine.rom]]
name="945_m08.n17"
size=131072
crc="74e981d2"
region="sub"
offset=0x000001
[[parse.machine.rom]]
name="945_l06b.r11"
size=131072
crc="83772304"
region="sub"
offset=0x040000
[[parse.machine.rom]]
name="945_l06a.n11"
size=131072
crc="e1fd75b6"
region="sub"
offset=0x040001
[[parse.machine.rom]]
name="945_l07c.r15"
size=131072
crc="c1e399b6"
region="sub"
offset=0x080000
[[parse.machine.rom]]
name="945_l07a.n15"
size=131072
crc="96222d04"
region="sub"
offset=0x080001
[[parse.machine.rom]]
name="945_l07d.r13"
size=131072
crc="4c16d4bd"
region="sub"
offset=0x0c0000
[[parse.machine.rom]]
name="945_l07b.n13"
size=131072
crc="5e209d01"
region="sub"
offset=0x0c0001

[[parse.machine.rom]]
name="945_r05.d9"
size=65536
crc="c8c45365"
region="audiocpu"
offset=0x00000

[[parse.machine.rom]]
name="945_a02.l3"
size=524288
crc="4dfffd74"
region="k051960"
offset=0x000000
[[parse.machine.rom]]
name="945_a01.h3"
size=524288
crc="339d6dd2"
region="k051960"
offset=0x000002
[[parse.machine.rom]]
name="945_l04a.k6"
size=131072
crc="884e21ee"
region="k051960"
offset=0x100000
[[parse.machine.rom]]
name="945_l04c.m6"
size=131072
crc="45bcd921"
region="k051960"
offset=0x100001
[[parse.machine.rom]]
name="945_l03a.e6"
size=131072
crc="a67ef087"
region="k051960"
offset=0x100002
[[parse.machine.rom]]
name="945_l03c.h6"
size=131072
crc="a56be17a"
region="k051960"
offset=0x100003
[[parse.machine.rom]]
name="945_l04b.k8"
size=131072
crc="843bc67d"
region="k051960"
offset=0x180000
[[parse.machine.rom]]
name="945_l04d.m8"
size=131072
crc="0a98d08e"
region="k051960"
offset=0x180001
[[parse.machine.rom]]
name="945_l03b.e8"
size=131072
crc="933e68b9"
region="k051960"
offset=0x180002
[[parse.machine.rom]]
name="945_l03d.h8"
size=131072
crc="f375e87b"
region="k051960"
offset=0x180003

[[parse.machine.rom]]
name="945l14.j28"
size=256
crc="c778c189"
region="proms"
offset=0x0000

[[parse.machine.rom]]
name="945_a10.b15"
size=262144
crc="1d083e10"
region="k007232"
offset=0x00000
[[parse.machine.rom]]
name="945_l11a.c18"
size=131072
crc="6043f4eb"
region="k007232"
offset=0x40000
[[parse.machine.rom]]
name="945_l11b.c20"
size=131072
crc="89ea3baf"
region="k007232"
offset=0x60000

[buttons]
names = [
    { machine="gradius3", names="Power-Up,Shoot,Missile" },
]

[dipsw]
bitcnt=20
delete=[{names=["Unused","Unknown"]}]

[ROM]
regions = [
    { name="maincpu", width=16, reverse=true },
    { name="sub",     start="JTFRAME_BA1_START", width=16, reverse=true },
    { name="k051960", start="GFX_START", width=32 },
    { name="audiocpu", start="JTFRAME_BA2_START" },
    { name="k007232",  start="PCM_START" },
    { name="proms",    start="JTFRAME_PROM_START" },
]

order = [ "maincpu", "sub", "k051960", "audiocpu", "k007232", "proms" ]
