../../hdl/jt1942_colmix.v
../../hdl/jt1942_game.v
../../hdl/jt1942_main.v
../../hdl/jt1942_sound.v
../../hdl/jt1942_video.v
../../hdl/jt1942_prom_we.v
../../hdl/jt1942_obj.v
../../hdl/jt1942_objram.v
../../hdl/jt1942_objdraw.v
../../hdl/jt1942_objtiming.v
../../hdl/jt1942_dip.v
../../../modules/jtgng_rom.v
../../../modules/jtgng_romrq.v
../../../modules/jtgng_romflex.v
../../../modules/jtgng_multiram.v
../../../modules/jtframe/hdl/jtframe_z80wait.v
../../../modules/jtgng_objpxl.v
../../../modules/jtgng_cen.v
../../../modules/jtgng_dual_ram.v
../../../modules/jtframe/hdl/ram/jtframe_ram.v
../../../modules/jtframe/hdl/ram/jtframe_prom.v
../../../modules/jtgng_sh.v
../../../modules/jtgng_true_dual_ram.v
../../../modules/jtgng_timer.v
../../../modules/jtgng_char.v
../../../modules/jtgng_scroll.v
../../../modules/jtgng_tilemap.v
../../../modules/jtgng_tile3.v
../../../modules/jtframe/hdl/ver/noise_gen.v

../../../modules/jtgng_charmsg.v
