[global]
author=["Andrea Bogazzi"]

[parse]
sourcefile=[ "blockout.cpp" ]
skip.setnames=["agress", "agressb"]

[header]
info = """ Header to identify the PCB type
        Byte 0 = 0 for blockout, 1 for blockoutj
"""
registers=[
    { name="blockout",    pos="0[0]",   desc="Blockout",   values=[{ setnames=["blockout","blockout2","blockout3"], value=1 }] },
    { name="blockoutj",    pos="0[1]",   desc="Blockoutj",  values=[{ setname="blockoutj", value=1 }] },
]

[buttons]
names=[
    { setnames=["blockout","blockout2","blockout3"], names="A,B,C,Drop"},
    { setname="blockoutj", names="Drop,B,C"}
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]
regions = [
    { name="maincpu",  width=16, reverse=true, no_offset=true },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="oki",      start="PCM_START" },
    { name="proms", skip=true },
]

order = [ "maincpu", "audiocpu", "oki" ]
