[global]
author=["Andrea Bogazzi"]

[parse]
sourcefile=[ "blockout.cpp" ]
skip.setnames=["aggress"]

[header]
info = """ Header to identify the PCB type
        Byte 0 = 0 for blockout, 1 for blockoutj
"""
data = [
    { machine="blockout",   offset=0, data="00" },
    { machine="blockoutj", offset=0, data="01" },
]

[buttons]
names=[
    { machine="blockout", names="A,B,C,Drop"},
    { machine="blockoutj", names="Drop,B,C"}
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]
regions = [
    { name="maincpu",  width=16, reverse=true, no_offset=true },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="oki",      start="PCM_START" },
]

order = [ "maincpu", "audiocpu", "oki" ]
