# fx68k_dummy.v
../../hdl/jttora_colmix.v
../../hdl/jttora_game.v
../../hdl/jttora_main.v
../../hdl/jttora_prom_we.v
../../hdl/jttora_video.v
../../hdl/jttora_dwnld.v
../../hdl/jttora_sound.v
../../../biocom/hdl/jtbiocom_mcu.v
../../../1943/hdl/jt1943_scroll.v
../../../modules/fx68k/fx68kAlu.sv
../../../modules/fx68k/fx68k.sv
../../../modules/fx68k/uaddrPla.sv
# ../../../modules/jt12/hdl/jt12_rst.v
../../../modules/jtframe/hdl/cpu/jtframe_z80.v
../../../modules/jtframe/hdl/cpu/jtframe_68kdma.v
../../../modules/jtframe/hdl/keyboard/jtframe_4wayjoy.v
../../../modules/jtframe/hdl/jtframe_z80wait.v
../../../modules/jtframe/hdl/ram/jtframe_prom.v
../../../modules/jtframe/hdl/ram/jtframe_ram.v
../../../modules/jtframe/hdl/clocking/jtframe_cencross_strobe.v
../../../modules/jtframe/hdl/ver/jtframe_din_check.v
../../../modules/jtframe/hdl/clocking/jtframe_cen48.v
../../../modules/jtframe/hdl/clocking/jtframe_cen24.v
../../../modules/jtframe/hdl/clocking/jtframe_frac_cen.v
../../../modules/jtframe/hdl/video/jtframe_blank.v
../../../modules/jtgng_charmsg.v
../../../modules/jtgng_char.v
../../../modules/jtgng_dual_ram.v
../../../modules/jtgng_multiram.v
../../../modules/jtgng_objbuf.v
../../../modules/jtgng_objdma.v
../../../modules/jtgng_objdraw.v
../../../modules/jtgng_objcnt.v
../../../modules/jtgng_objpxl.v
../../../modules/jtgng_obj.v
../../../modules/jtgng_avatar.v
../../../modules/jtgng_avatar_pal.v
../../../modules/jtgng_obj32.v
../../../modules/jtframe/hdl/sdram/jtframe_avatar.v
../../../modules/jtframe/hdl/sdram/jtframe_rom.v
../../../modules/jtframe/hdl/sdram/jtframe_romrq.v
../../../modules/jtframe/hdl/ram/jtframe_dual_ram.v
../../../modules/jtframe/hdl/jtframe_sh.v
../../../modules/jtgng_tile4.v
../../../modules/jtgng_tilemap.v
../../../modules/jtgng_timer.v
../../../modules/jtgng_true_dual_ram.v
../../../modules/jtgng_sound.v
../../../modules/jt12/jt49/hdl/filter/jt49_dcrm2.v
../../../modules/jt12/hdl/mixer/jt12_mixer.v
