all: sdram_bank0.bin sdram_bank1.bin sdram_bank2.bin sdram_bank3.bin

sdram_bank0.bin:
	dd if=/dev/urandom of=sdram_bank0.bin bs=1M count=8

sdram_bank1.bin:
	dd if=/dev/urandom of=sdram_bank1.bin bs=1M count=8

sdram_bank2.bin:
	dd if=/dev/urandom of=sdram_bank2.bin bs=1M count=8

sdram_bank3.bin:
	dd if=/dev/urandom of=sdram_bank3.bin bs=1M count=8
