/*  {{ .Module }}.v was generated by jtframe mmr.
    Do not edit this generated file directly.
    Edit cfg/mmr.yaml or modules/jtframe/hdl/inc/mmr.v instead.
    Do not add generated *_mmr.v files to git. */
{{ $is_16bit := 0 }}{{ if eq .Dw 16 }}{{ $is_16bit = 1 }}{{ end }}
module {{ .Module }}(
    input             rst,
    input             clk,

    input             cs,
    input       [{{.AMSB}}:{{$is_16bit}}] addr,
    input             rnw,
    input       [{{ sub .Dw 1 }}:0] din, {{ if not .Read_only }}
    output reg  [{{ sub .Dw 1 }}:0] dout, {{- end }}{{ if $is_16bit }}
    input       [1:0] dsn,
    {{- end }}
    {{ range .Regs }}
    output {{if .IsEvent }}reg  {{else}}{{if eq .Dw 1}}     {{else}}[{{ sub .Dw 1 }}:0]{{end}}{{ end }} {{ .Name }},
    {{- end }}

    // IOCTL dump
    input      [{{.AMSB}}:0] ioctl_addr,
    output reg [7:0] ioctl_din,
    // Debug
    input      [7:0] debug_bus,
    output reg [7:0] st_dout
);

localparam SIZE={{.Size}};
parameter SIMFILE="rest.bin",
          SEEK=0;
parameter [SIZE*8-1:0] INIT=0; // from high to low regs {mmr[3],mmr[2],mmr[1],mmr[0]}


reg  [ 7:0] mmr[0:SIZE-1];
integer     i;
`ifdef SIMULATION
reg [7:0] mmr_init[0:SIZE-1];
`endif
{{ range .Regs }}{{ if not .IsEvent }}{{ $chunks := .Chunks }}
assign {{.Name}} = {
{{- range $idx, $chunk := $chunks }}
    mmr[{{$chunk.Byte}}][{{if eq $chunk.Msb $chunk.Lsb}}{{$chunk.Msb}}{{else}}{{$chunk.Msb}}:{{$chunk.Lsb}}{{end}}]{{ if lt (add1 $idx) (len $chunks) }},{{end}}
{{- end }}
    };
{{end}}{{ end }}

always @(posedge clk) begin
    if( rst ) begin
    `ifndef SIMULATION
        for(i=0;i<SIZE;i=i+1) mmr[i] <= INIT[i*8+:8];
    `else
        for(i=0;i<SIZE;i=i+1) mmr[i] <= mmr_init[i];
    `endif {{ range .Regs }}{{ if .IsEvent }}
        {{.Name}} <= 0; {{ end }}{{- end }}{{ if not .Read_only }}
    dout <= 0; {{- end }}
    end else begin{{ range .Regs }}{{ if .IsEvent }}
        {{.Name}} <= 0; {{ end }}{{- end }}{{ if not .Read_only }}{{ if $is_16bit }}
        dout      <= {mmr[{addr,1'b1}],mmr[{addr,1'b0}]};{{else}}
        dout      <= mmr[addr];{{end}}{{- end }}
        st_dout   <= mmr[debug_bus[{{.AMSB}}:0]];
        ioctl_din <= mmr[ioctl_addr];
        if( cs & ~rnw ) begin{{ if $is_16bit }}
            if(!dsn[0]) mmr[{addr,1'b0}]<=din[ 7:0];
            if(!dsn[1]) mmr[{addr,1'b1}]<=din[15:8];{{else}}
            mmr[addr]<=din;{{end}}
        end{{ range .Regs }}{{ if .IsEvent }}
        if({{.EventCond}}) {{.Name}} <= 1;{{ end }}{{- end }}
        i = 0; // for Quartus linter
    end
end

`ifdef SIMULATION
/* verilator tracing_off */
integer f, fcnt, err;
initial begin
    f=$fopen(SIMFILE,"rb");
    err=$fseek(f,SEEK,0);
    if( f!=0 && err!=0 ) begin
        $display("Cannot seek file rest.bin to offset 0x%0X (%0d)",SEEK,SEEK);
    end
    if( f!=0 ) begin
        fcnt=$fread(mmr_init,f);
        $display("MMR %m - read %0d bytes from offset %0d",fcnt,SEEK);
        if( fcnt!=SIZE ) begin
            $display("WARNING: Missing %d bytes for %m.mmr",SIZE-fcnt);
        end else begin{{ range .Regs }}{{ if not .IsEvent }}{{ $chunks := .Chunks }}
            $display("\t{{.Name}} = %X",{ {{range $idx, $chunk := $chunks}}mmr_init[{{$chunk.Byte}}][{{if eq $chunk.Msb $chunk.Lsb}}{{$chunk.Msb}}{{else}}{{$chunk.Msb}}:{{$chunk.Lsb}}{{end}}]{{ if lt (add1 $idx) (len $chunks) }}, {{end}}{{end}} });
            {{- end }}{{ end }}
        end
    end else begin
        for(i=0;i<SIZE;i=i+1) mmr_init[i] = 0;
    end
    $fclose(f);
end
`endif

endmodule
