// generated by ver/audio/emit.py - do not edit
localparam SECTIONS  = 68;
localparam BSH       = 26;
localparam TONE_TH   = 8'd166;
localparam PULSE_TK  = 6'd16;
localparam RECOV_TK  = 6'd36;
localparam KRAMP     = 17'd340;
localparam signed [16:0] TGT_LOUD = 17'sd32767;
localparam signed [16:0] TGT_SOFT = -17'sd4965;
localparam [15:0] DUCK_G = 16'd25093;
localparam [8*16-1:0] LADDER = {16'd792,16'd1882,16'd4248,16'd7962,16'd12763,16'd21477,16'd28130,16'd32767};
