[parse]
sourcefile=[ "twin16.cpp" ]
parents= [
    {name="mia",description="Missing in Action"},
    {name="cuebrick",description="Cuebrick"}
]
skip = { setnames=[
    "fround","froundl", # in fround core
    "hpuncher" # PROMs not supported
] }
debug = { machines=["mia"] }

[buttons]
names=[
    { machine="devilw", names="Power up,Shoot,Jump" },
    { machine="vulcan", names="Special power,Shoot,Missile" },
    { machine="mia",  names="Knife, Weapon, Weapon select" },
    { machine="cuebrick",  names="Move, Warp, Stop" },
]

[dipsw]
delete=[{names=["Unused","Unknown"]}]

[ROM]
# values starting with $ refer to macro definitions in the .def file
# or arguments passed to mame2mra
regions = [
    { name="maincpu", width=16, reverse=true  },
    # bank 1
    { name="sub",     width=16, reverse=true, start="JTFRAME_BA1_START"  },
    { name="data",    width=16, reverse=true  },
    { name="data",    skip=true, machines=["mia", "vulcan"]},
    { name="gfxrom",  start="GFX_START", width=32 },
    { name="gfxrom",  skip=true, setname="cuebrickj" },
    # bank 2
    { name="fixed",   start="JTFRAME_BA2_START"   },
    # bank 3
    { name="audiocpu",start="JTFRAME_BA3_START" },
    { name="k007232", start="PCM_START"  },
    { name="upd",     start="UPD_START"  },
]

order = [
    "maincpu", "sub", "data", "gfxrom",
    "fixed", "audiocpu", "k007232", "upd"
]

patches = [
    # bypass check screen. Object RAM test fails randomly because of
    # DMA writes while the check is performed
    # this patch works on simulation but fails on FPGA :-(
    # { setname="cuebrickj", offset=0x100, data="71 4E 71 4E 71 4E" }
]