[global]
mraauthor=["jotego"]
platform="jtkiwi"

[parse]
sourcefile=[ "tnzs.cpp" ]
skip = { setnames = [
    # Inputs not working
    "plumppop",     # most left column missing, see service screen
    "chukatai",     # top screen row missing for objects plus garbage at top left
    "chukataij",
    "chukataija",
    "chukataiu",

    # Three Z80
    #"kabukiz",
    #"kabukizj",
    "tnzs",
    "tnzsj",
    # Korean hack on mostly unrelated hardware
    "jpopnics",
] }
main_setnames=[ "tnzso" ]

[header]
info="""bit 0 = MCU
             bit 1 = color PROM
             bit 2 = Kabuzi Z (specific sound features)
             bit 3 = Kageki   (specific sound features)
             bit 4 = banked RAM
             bit 5 = coin XOR
             bit 6 = dip_flip XOR
             bit 7 = HB delay
             Byte 1:
             bit 0 = service XOR
             bit 1 = button aid
             bit 2 = 3 MHz for FM module                 """
data=[
    { setnames=["tnzso","tnzsjo","tnzsoa","tnzsop","tnzsuo"], data="B1 04" }, # HB dly, Banked RAM, MCU, 3MHz FM
    { machines=["chukatai"], data="41" }, # MCU
    { machines=["insectx"],  data="40" }, # dip_flip inversion
    { machines=["drtoppel"], data="03" },
    { machines=["extrmatn","plumppop" ], data="03" }, # MCU - Color PROM
    { machines=["arknoid2"], data="03 03" }, # MCU - Color PROM, Service XOR, Button aid
    { machine="kabukiz",  data="04" }, # Kabuki Z sound subsystem
    { machine="kageki" ,  data="08" }, # Kageki   sound subsystem
]

[buttons]
Names = [ { machine="insectx",  names="Fire,Warp"},
          { machine="extrmatn", names="Fire,Warp"},
          { machine="tnzs",     names="Shoot,Jump"},
          { machine="kageki",   names="Left jab,Right hook"},
          { machine="arknoid2", names="Shoot"},
]

[dipsw]
bitcnt = 16
delete=[{names=["Unused","Unknown"]}]
rename = [{ name="P1 & P2 Children Collision", to="P1/P2 Collision" }]

[ROM]
regions = [
    { name="maincpu", No_offset=true   },
    { name="sub", start="JTFRAME_BA1_START" },
    { name="audiocpu", start="JTFRAME_BA2_START" },
    { name="samples", start="PCM_START" },
    { name="gfx1", start="JTFRAME_BA3_START", width=32, sequence=[2,0,3,1] },
    { machines=["kageki", "tnzs", "chukatai","drtoppel" ], name="gfx1", start="JTFRAME_BA3_START", width=32, sequence=[4,0,6,2, 5,1,7,3] },
    { machines=["plumppop"], name="gfx1", start="JTFRAME_BA3_START", width=32, sequence=[4,0,6,2, 4,0,6,2, 5,1,7,3, 5,1,7,3 ] },
    { machine="insectx",           name="gfx1", start="JTFRAME_BA3_START", width=16, no_offset=true },
    { name="proms", start="JTFRAME_PROM_START", No_offset=true },
    { name="mcu", start="MCU_START", No_offset=true, len=0x800, custom={ dev="8042" } },
    { name="pal", skip=true },
]

order = [
    "maincpu", "sub", "audiocpu", "samples",
    "gfx1", "proms", "mcu"
]


