[global]
author=["jotego"]

[parse]
sourcefile=[ "gunsmoke.cpp" ]
skip.setnames=[
    # dump unavailable
    "gunsmokeua",
    # won't boot
    "gunsmokeub",
]

[Audio]
volume = [
    { machine="gunsmoke", value=0x8C },
]

[buttons]
names=[
    { names="Shoot left,Shoot centre,Shoot right" }
]

[ROM]
regions=[
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="chars",    start="CHAR_START", reverse=true },
    { name="bgtiles",  start="JTFRAME_BA2_START", reverse=true },
    { name="tiles",    start="JTFRAME_BA3_START", width=16, no_offset=true, sequence=[4,0,5,1,6,2,7,3]  },
    { name="sprites",  start="OBJ_START",         width=16, no_offset=true, sequence=[4,0,5,1,6,2,7,3]  },
    { name="proms",    start="JTFRAME_PROM_START" },
]

order=[
    "maincpu","audiocpu",
    "chars", "bgtiles",
    "tiles", "sprites", "proms"
]