[parse]
sourcefile=[ "twincobr.cpp" ]
skip.setnames=[ "fsharkb", "hishouzab", "fsharkbt", "fnshark", "gulfwar2", "gulfwar2a" ]

[buttons]
names=[
    { names="Shot,Bomb" },
]

[header]
registers = [
    { name="tcobr", pos="0[0]", desc="Twin Cobra board", values=[{ machine="twincobr", value=1 }] },
    { name="fast",  pos="0[1]", desc="68000 at 10 MHz",  values=[{ setnames=["twincobr","twincobru"], value=1 }] },
]

[dipsw]
bitcnt = 16
delete = [{ names=[ "Unused", "Unknown" ] }]

[ROM]
regions = [
    { name="maincpu",  width=16, reverse=true },
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="dsp",      start="DSP_START", width=16, reverse=true },
    { name="chars",    width=32, start="JTFRAME_BA2_START", sequence=[0,1,2,2] },
    { name="bg_tiles", width=32, start="BG_START",  sequence=[0,1,2,3] },
    { name="fg_tiles", width=32, start="FG_START",  sequence=[0,1,2,3] },
    { name="scu",      rename="obj", width=32, start="JTFRAME_BA3_START", sequence=[0,1,2,3] },
    { name="proms",    start="JTFRAME_PROM_START" },
]

order = [
    "maincpu", "audiocpu", "dsp", "chars", "bg_tiles", "fg_tiles", "obj", "proms"
]
