/* SPDX-FileCopyrightText: 2026 Jose Tejada Gomez
 * SPDX-License-Identifier: GPL-3.0-or-later
 * Date: 26-1-2025 */

module jtframe_debug_viewmux(
    input            rst, clk,
                     toggle,

    input      [7:0] debug_view, // an 8-bit signal that will be shown over the game image
    input      [7:0] sys_info,   // system information generated within JTFRAME, not the game
    input      [7:0] target_info,  // system information generated by the JTFRAME target, not the game
    input            snd_mode,
    input      [7:0] snd_vol,

    output reg       split_binhex=0,
    output reg [1:0] sel=0,
    output reg [7:0] view_bin=0,
    output reg [7:0] view_hex=0
);    

`include "jtframe_debug.vh"

reg  [7:0] mux;
reg        toggle_l=0;

always @(posedge clk) begin
    if( rst ) begin
        toggle_l <= 0;
    end else begin
        toggle_l <= toggle;

        if( toggle && !toggle_l ) begin
            sel <= sel==2 ? 2'd0 : sel+1'd1;
        end
    end
end

always @(posedge clk) begin
    case( sel )
        default:     mux <= debug_view;
        SYS_INFO:    mux <= sys_info;
        TARGET_INFO: mux <= target_info;
    endcase
    split_binhex <= sel==SYS_INFO && snd_mode;

    view_bin <= mux;
    view_hex <= split_binhex ? snd_vol : view_bin;
end

endmodule