set_global_assignment -name VERILOG_MACRO "CORENAME=\"JTBIOCOM\""
set_global_assignment -name VERILOG_MACRO "HAS_TESTMODE=1"
set_global_assignment -name VERILOG_MACRO "GAMETOP=jtbiocom_game"
set_global_assignment -name VERILOG_MACRO "MISTTOP=jtbiocom_mist"
set_global_assignment -name VERILOG_MACRO "STEREO_GAME=1"
set_global_assignment -name VERILOG_MACRO "COLORW=5"
