/*  jtddribble_game.v — Double Dribble (Konami GX690) top-level
    Wires the main/sub/sound MC6809Es, the video pipeline (jtddribble_video),
    and the shared-SRAM / palette BRAMs.
    GPL3 — see jtcores LICENSE
*/

module jtddribble_game(
    `include "jtframe_game_ports.inc"
);

// ---------------------------------------------------------------------------
// Internal wires between sub-modules
// ---------------------------------------------------------------------------
wire [15:0] main_A;           // raw 16-bit address from main CPU
wire        main_rnw;         // 1 = read, 0 = write
wire [ 7:0] main_dout;        // CPU data output

// Per-region chip-selects (generated by main)
// VRAM/sprite chip-selects are NOT here — they are now folded into k5885_1_cs / k5885_2_cs
// because on the real PCB each 005885 owns its private 6264SL SRAM (CPU goes through the
// chip, not directly to the SRAM). See doc/005885_implementation.md.
wire        pal_cs, shared_cs;
wire        k5885_1_cs, k5885_2_cs;
wire [ 7:0] k5885_1_dout, k5885_2_dout;        // read-back from each 005885 (8'hff until module exists)
wire [ 2:0] main_bank;                          // 3-bit bank-switch register from main CPU (0x8000 latch)

// ---------------------------------------------------------------------------
// Main CPU sub-module
// ---------------------------------------------------------------------------
`ifndef NOMAIN
jtddribble_main u_main(
    .rst         ( rst        ),
    .clk         ( clk        ),
    .cen         ( cpu_cen    ),     // 1.5 MHz, from mem.yaml clocks block
    .cpu_cen     (            ),     // Q-phase strobe — unused this round
    // ROM
    .rom_addr    ( main_addr  ),     // 16-bit address → SDRAM 'main' bus
    .rom_cs      ( main_cs    ),
    .rom_data    ( main_data  ),
    .rom_ok      ( main_ok    ),
    // CPU bus exposed for downstream decoders
    .A           ( main_A     ),
    .cpu_rnw     ( main_rnw   ),
    .cpu_dout    ( main_dout  ),
    // Chip-selects (outputs from main)
    .pal_cs       ( pal_cs       ),     // 007327 palette
    .shared_cs    ( shared_cs    ),     // 0x4000-0x5FFF main↔sub shared
    .k5885_1_cs   ( k5885_1_cs   ),     // 005885 #1 (regs 0x0000-0x0004 + VRAM 0x2000-0x3FFF)
    .k5885_2_cs   ( k5885_2_cs   ),     // 005885 #2 (regs 0x0800-0x0804 + VRAM 0x6000-0x7FFF)
    // Data back to CPU
    .pal_dout     ( pal_dout       ),       // 007327 palette RAM CPU read-back
    .shared_dout  ( shared_ms_dout ),       // from the shared_ms BRAM (side A)
    .k5885_1_dout ( k5885_1_dout   ),       // 005885 chip 1 read-back (DBo, via jtddribble_video)
    .k5885_2_dout ( k5885_2_dout   ),       // 005885 chip 2 read-back (DBo, via jtddribble_video)
    // Bank-switch register — 3 bits, latched on CPU write to 0x8000.
    .bank_out     ( main_bank      ),
    // Interrupts — chip 1 (E16) fans NFIR/NIRQ/NNMI to BOTH CPUs via the
    // 1 kΩ pull-up shared bus on the schematic. NOTE the IRQ/FIRQ wire
    // swap vs the chip's pin names (per schematic 2026-06-01):
    //   chip NFIR → CPU IRQ pin
    //   chip NIRQ → CPU FIRQ pin
    //   chip NNMI → CPU NMI pin
    .cpu_irqn    ( k5885_1_NFIR ),     // chip NFIR  → main IRQ
    .cpu_nmin    ( k5885_1_NNMI ),     // chip NNMI  → main NMI
    .cpu_firqn   ( k5885_1_NIRQ )      // chip NIRQ  → main FIRQ
);
`else
// ---------------------------------------------------------------------------
// Scene replay: jtsim -s adds NOMAIN. Stub the main CPU so it never writes
// the 005885 tile/sprite RAMs or the 007327 palette. The scene state loaded
// into those BRAMs via SIMFILE (gfx{1,2}_{attr,code,obj}.bin, pal.bin) then
// survives and is rendered exactly as captured from MAME.
// main_rnw held high (read) => attr/code/obj/pal write-enables never assert.
// ---------------------------------------------------------------------------
assign main_addr  = 16'd0;
assign main_cs    = 1'b0;
assign main_A     = 16'd0;
assign main_rnw   = 1'b1;
assign main_dout  = 8'd0;
assign pal_cs     = 1'b0;
assign shared_cs  = 1'b0;
assign k5885_1_cs = 1'b0;
assign k5885_2_cs = 1'b0;
assign main_bank  = 3'd0;
`endif

// ---------------------------------------------------------------------------
// Sub CPU sub-module
// ---------------------------------------------------------------------------
wire [15:0] sub_A;                       // sub CPU address bus (exposed for BRAM addressing)
wire [ 7:0] sub_dout;
wire        sub_rnw;
wire        sub_shared_ms_cs, sub_shared_sa_cs;
wire        sub_wdog_kick;
wire [ 1:0] sub_coin_counter;

// ---------------------------------------------------------------------------
// Input matrix 
// ---------------------------------------------------------------------------
// Schematic page Back, mid to bottom left side
wire [7:0] p1_bytes = { 1'b1,
                          joystick1[5], joystick1[6], joystick1[4],   // B2, B3, B1
                          joystick1[0], joystick1[1],                  // DOWN, UP
                          joystick1[2], joystick1[3] };                // RIGHT, LEFT
wire [7:0] p2_bytes = { 1'b1,
                          joystick2[5], joystick2[6], joystick2[4],
                          joystick2[0], joystick2[1],
                          joystick2[2], joystick2[3] };
// SYSTEM byte (KONAMI8_SYSTEM_UNK): bit 0 = COIN1, 1 = COIN2,
// 2 = SERVICE, 3 = START1, 4 = START2, 5..7 unused (=1, not pressed)
wire [7:0] sys_byte = { 3'b111,
                          cab_1p[1], cab_1p[0], service,
                          coin[1], coin[0] };
// DSW slicing — convention: dipsw[7:0]=DSW1, [15:8]=DSW2, [23:16]=DSW3.
wire [7:0] dsw1_byte = dipsw[ 7: 0];
wire [7:0] dsw2_byte = dipsw[15: 8];
wire [7:0] dsw3_byte = dipsw[23:16];

jtddribble_sub u_sub(
    .rst            ( rst        ),
    .clk            ( clk        ),
    .cen            ( cpu_cen    ),
    .cpu_cen        (            ),
    .rom_addr       ( sub_addr   ),     // → SDRAM region 'sub' from mem.yaml
    .rom_cs         ( sub_cs     ),
    .rom_data       ( sub_data   ),
    .rom_ok         ( sub_ok     ),
    .A              ( sub_A             ),
    .cpu_rnw        ( sub_rnw           ),
    .cpu_dout       ( sub_dout          ),
    .shared_ms_cs   ( sub_shared_ms_cs  ),
    .shared_sa_cs   ( sub_shared_sa_cs  ),
    .shared_ms_dout ( shared_ms_b_dout  ),     // from the shared_ms BRAM (side B)
    .shared_sa_dout ( shared_sa_dout    ),     // from the shared_sa BRAM (sub↔sound)
    .dsw1           ( dsw1_byte    ),
    .dsw2           ( dsw2_byte    ),
    .dsw3           ( dsw3_byte    ),
    .p1_input       ( p1_bytes     ),
    .p2_input       ( p2_bytes     ),
    .system_input   ( sys_byte     ),
    .coin_counter   ( sub_coin_counter ),
    .wdog_kick      ( sub_wdog_kick    ),
    // Interrupts — chip 1 (E16) fans the SAME signals to both CPUs (per
    // schematic 2026-06-01). Same NFIR↔IRQ / NIRQ↔FIRQ swap as main.
    .cpu_irqn       ( k5885_1_NFIR ),    // chip NFIR  → sub IRQ
    .cpu_nmin       ( k5885_1_NNMI ),    // chip NNMI  → sub NMI
    .cpu_firqn      ( k5885_1_NIRQ )     // chip NIRQ  → sub FIRQ
);

// ---------------------------------------------------------------------------
// MAIN <-> SUB shared SRAM dual-port wiring
// ---------------------------------------------------------------------------
// SCHEMATIC: the physical shared SRAM chip on the PCB hasn't been pinpointed
// yet — likely a 6264 (8 K x 8 SRAM) reachable from both pages, accessible
// via the main CPU side (A19, page 0, /CWORK strobe from 007552 pin 15) and
// the sub CPU side (A12, page 1, /CRAM strobe from 007553 pin 13). The
// bus-arbitration logic that picks which
// CPU "owns" the SRAM each cycle is in hardware via LS157 muxes; in our HDL
// the dual-port BRAM (declared in mem.yaml as 'shared_ms') gives both CPUs
// independent access — no arbitration needed in simulation.

// Side A — connected to MAIN CPU bus
//   Address: lower 13 bits of MAIN address (0x4000-0x5FFF maps directly to BRAM 0x0-0x1FFF)
assign shared_ms_addr = main_A[12:0];
assign shared_ms_din  = main_dout;
assign shared_ms_we   = shared_cs && !main_rnw;

// Side B — connected to SUB CPU bus
//   Address: lower 13 bits of SUB address (0x0000-0x1FFF directly)
assign shared_ms_b_addr = sub_A[12:0];
assign shared_ms_b_din  = sub_dout;
assign shared_ms_b_we   = sub_shared_ms_cs && !sub_rnw;

// ---------------------------------------------------------------------------
// MAIN CPU's exclusive BRAMs
// ---------------------------------------------------------------------------
// Only palette RAM remains externally addressable. The fgvram/bgvram/spr1/spr2
// regions are NOT separate BRAMs — they live inside the 005885 chip's private
// 6264SL SRAM, accessed by the CPU through the 005885's CPU-bus interface.
// See doc/005885_implementation.md for the topology.

// Palette RAM — 128 B (7-bit address). On the real PCB it lives inside the
// 007327; here it is a mem.yaml `pal` BRAM read by jtddribble_colmix (the 007327
// model), CPU write side wired below.
assign pal_addr    = main_A[6:0];
assign pal_din     = main_dout;
assign pal_we      = pal_cs    && !main_rnw;

// ---------------------------------------------------------------------------
// Video pipeline — jtddribble_video holds BOTH 005885 instances + their VRAM
// BRAMs AND the jtddribble_colmix (007327 palette + LS157/LS32 priority). It
// drives the framework RGB directly and owns the video sync; game.v only routes
// its gfx ROM buses and the `pal` BRAM read port.
// ---------------------------------------------------------------------------
wire        k5885_1_NIRQ, k5885_1_NNMI, k5885_1_NFIR;
wire [15:0] k5885_1_R,    k5885_2_R;
wire        k5885_1_RA16, k5885_1_RA17, k5885_1_rom_cs;
wire        k5885_2_RA16, k5885_2_RA17, k5885_2_rom_cs;

jtddribble_video u_video(
    .rst            ( rst            ),
    .clk            ( clk            ),
    .clk24          ( clk24          ),
    .pxl_cen        ( pxl_cen        ),
    .pxl2_cen       ( pxl2_cen       ),
    .cpu_cen        ( cpu_cen        ),
    // CPU bus
    .main_A         ( main_A         ),
    .main_dout      ( main_dout      ),
    .main_rnw       ( main_rnw       ),
    .k5885_1_cs     ( k5885_1_cs     ),
    .k5885_2_cs     ( k5885_2_cs     ),
    .k5885_1_dout   ( k5885_1_dout   ),
    .k5885_2_dout   ( k5885_2_dout   ),
    // gfx ROM (game.v maps R/RA1x to gfx{1,2}_addr below)
    .k5885_1_R      ( k5885_1_R      ),
    .k5885_1_RA16   ( k5885_1_RA16   ),
    .k5885_1_RA17   ( k5885_1_RA17   ),
    .k5885_1_rom_cs ( k5885_1_rom_cs ),
    .gfx1_data      ( gfx1_data      ),
    .gfx1_ok        ( gfx1_ok        ),
    .k5885_2_R      ( k5885_2_R      ),
    .k5885_2_RA16   ( k5885_2_RA16   ),
    .k5885_2_RA17   ( k5885_2_RA17   ),
    .k5885_2_rom_cs ( k5885_2_rom_cs ),
    .gfx2_data      ( gfx2_data      ),
    .gfx2_ok        ( gfx2_ok        ),
    // interrupts (chip 1 fans to both CPUs)
    .k5885_1_NFIR   ( k5885_1_NFIR   ),
    .k5885_1_NIRQ   ( k5885_1_NIRQ   ),
    .k5885_1_NNMI   ( k5885_1_NNMI   ),
    // chip-owned video sync to the framework
    .LHBL           ( LHBL           ),
    .LVBL           ( LVBL           ),
    .HS             ( HS             ),
    .VS             ( VS             ),
    // palette BRAM read port (CPU-write side wired above via pal_cs)
    .pal_v_addr     ( pal_v_addr     ),
    .pal_v_dout     ( pal_v_dout     ),
    // RGB to the framework — the colmix lives inside u_video now
    .red            ( red            ),
    .green          ( green          ),
    .blue           ( blue           ),
    // sprite-lookup PROM load
    .prog_addr      ( prog_addr[8:0] ),
    .prog_data      ( prog_data[3:0] ),
    .prom_we        ( prom_we        ),
    .debug_bus      ( debug_bus      ),
    .gfx_en         ( gfx_en         )
);

// ---------------------------------------------------------------------------
// SDRAM gfx ROM routing
// ---------------------------------------------------------------------------
// gfx1 region (mem.yaml) → chip 1's R[15:0] / RDU+RDL bus
// The wrapper presents R[15:0] as a word address (one fetch = 16 bits =
// one tile pattern byte-pair). JTFRAME's gfx1_addr is also word-addressed
// — it's declared [16:1] specifically to flag bit-0 as implicit-zero.
// Direct Verilog assignment lines up the LSBs correctly:
//   gfx1_addr[1]  ← k5885_1_R[0]   (LSB)
// gfx1: chip drives R[15:0] + RA16 + RA17. gfx1 is 256 KB (2x MASK1M) = a 17-bit
// WORD address, so only R + RA16 are used. mem.yaml addr_width=18 makes gfx1_addr
// [17:1] (17 bits) so {RA16,R} lands without truncation. (At 17 it was [16:1] and
// truncated RA16 -> sprites read the chars half instead of objects — the bug that
// hid for weeks because chars are RA16=0 and rendered fine.)
// RA17 is NOT wired to the gfx1 ROMs on the PCB; it must stay 0. We deliberately
// drop it here AND assert it below, so it can never silently truncate like RA16.
assign gfx1_addr = { k5885_1_RA16, k5885_1_R };
assign gfx1_cs   = k5885_1_rom_cs;


// gfx2: chip's RA0..RA15 + RA16,RA17 = 18-bit word address (512 KB), all USED
// (4x MASK1M). mem.yaml addr_width=19 makes gfx2_addr [18:1] = 18 bits so the
// full {RA17,RA16,R} lands without truncation. RA17 → bit 18, RA16 → bit 17
// (the same role the LS74 chain B15/A10/A11 plays on
// the real PCB, latching CHARA/CHAF2 to generate R17/R16).
//
// Replaces the prior `{ main_bank[0], k5885_2_R }` guess, which used
// the main CPU's 0x8000 bank latch as the MSB. That was wrong: bank
// switching belongs to the main CPU's program-ROM access, not chip 2's
// tile/sprite ROM access. With this fix chip 2 can finally reach the
// upper 256 KB of gfx2 (objects/sprite tile patterns at MAME byte
// offset 0x40000-0x7FFFF).
assign gfx2_addr = { k5885_2_RA17, k5885_2_RA16, k5885_2_R };
assign gfx2_cs   = k5885_2_rom_cs;

// (Video-side BRAM addresses + RGB + sync are now driven by jtddribble_video
//  instantiated near the end of this file.)

// ---------------------------------------------------------------------------
// SUB <-> SOUND shared SRAM dual-port wiring
// ---------------------------------------------------------------------------
// MAME map (ddribble.cpp:401, 415):
//   sub 0x2000-0x27FF  ←→  sound 0x0000-0x07FF   (same 2 KB BRAM, two ports)
// SCHEMATIC: the physical 2128SL (2 KB SRAM) visible on page 1 near the sound
// CPU is the strong candidate for this chip — see VERIFICATIONS.md section C.
//
// Side A — connected to SUB CPU bus
//   sub addresses 0x2000-0x27FF; lower 11 bits = BRAM index
assign shared_sa_addr = sub_A[10:0];
assign shared_sa_din  = sub_dout;
assign shared_sa_we   = sub_shared_sa_cs && !sub_rnw;

// Side B — connected to SOUND CPU bus
//   sound addresses 0x0000-0x07FF directly; lower 11 bits = BRAM index
assign shared_sa_b_addr = sound_A[10:0];
assign shared_sa_b_din  = sound_dout;
assign shared_sa_b_we   = sound_shared_cs && !sound_rnw;


// ---------------------------------------------------------------------------
// Sound CPU sub-module
// ---------------------------------------------------------------------------
wire [15:0] sound_A;                     // sound CPU address bus (for BRAM addressing)
wire [ 7:0] sound_dout;
wire        sound_rnw;
wire        sound_shared_cs, sound_ym_cs, sound_vlm_cs;

jtddribble_sound u_sound(
    .rst         ( rst        ),
    .clk         ( clk        ),
    .clk24       ( clk24      ),     // VLM5030 runs here (timing + its clk24 cen)
    .cen         ( sndcpu_cen ),     // own [snd]-gated 1.5 MHz cen — decoupled from main/sub SDRAM stalls
    .cpu_cen     (            ),
    .rom_addr    ( snd_addr   ),     // → SDRAM region 'snd' from mem.yaml
    .rom_cs      ( snd_cs     ),
    .rom_data    ( snd_data   ),
    .rom_ok      ( snd_ok     ),
    .A           ( sound_A    ),    
    .cpu_rnw     ( sound_rnw  ),
    .cpu_dout    ( sound_dout ),
    .shared_cs   ( sound_shared_cs ),
    .ym_cs       ( sound_ym_cs ),
    .vlm_cs      ( sound_vlm_cs ),
    .shared_dout ( shared_sa_b_dout ),     // from shared_sa BRAM
    .ym_cen      ( ym_cen     ),        // 3.58 MHz from mem.yaml
    .vlm_cen     ( vlm_cen    ),        // 3.58 MHz from mem.yaml
    .HS          ( HS         ),        // sound-IRQ scanline counter clock (NSYNC)
    .VS          ( VS         ),        // sound-IRQ counter reset (NVSYNC)
    .vlm_addr    ( vlm_addr   ),        // → SDRAM 'vlm' region (128 KB)
    .vlm_data    ( vlm_data   ),
    .vlm_ok      ( vlm_ok     ),
    .fm_snd      ( fm         ),     // → mem.yaml channel 'fm'
    .psg_snd     ( psg        ),     // → mem.yaml channel 'psg'
    .vlm_snd     ( vlm        )      // → mem.yaml channel 'vlm'
);

// Bridge the sound CPU's VLM voice-ROM CS to the framework's SDRAM port so the
// VLM5030 gets its voice data.
assign vlm_cs = sound_vlm_cs;

// Colour mixing (007327 palette + LS157/LS32 priority) now lives inside
// jtddribble_video (u_colmix), driven by the two 005885 COL buses there.

// OSD / debug
assign dip_flip  = 0;
assign debug_view= 0;

endmodule