#!/bin/bash
TOP=jtcps2_sbox_fn1_r1

verilator ../../hdl/jtcps2_{fn_,}sbox.v -cc test.cc cps2crypt.cpp -exe --top-module $TOP
export CPPFLAGS="$CPPFLAGS -O2"

if ! make -j -C obj_dir -f V${TOP}.mk V${TOP} > make.log; then
    cat make.log
    exit $?
else
    rm make.log
fi

obj_dir/V$TOP
