../../../modules/jtframe/hdl/cpu/jtframe_z80.v
../../../modules/jtframe/hdl/jtframe_z80wait.v
../../../modules/jtframe/hdl/ram/jtframe_ram.v
../../../modules/jtgng_cen.v
../../../modules/jtgng_cenp384.v
../../../modules/jtgng_cen3p57.v
../../../modules/jtgng_sound.v
../../../modules/jtgng_obj32.v
../../../modules/jt12/jt49/hdl/filter/jt49_dcrm2.v
../../../modules/jt12/hdl/mixer/jt12_mixer.v
../../hdl/jttora_adpcm.v
