[global]
author=["jotego"]

[parse]
sourcefile=[ "commando.cpp" ]
# The first byte in these games is encoded, opposite to
# other games
skip.Setnames=["sinvasnb","mercenario","commandob"]

[Audio]
volume = [
    { machine="commando", value=0x28 },
]

[buttons]
names=[
    { names="Shoot,Grenade" }
]

[dipsw]
delete=[ { names=[ "Cabinet" ] } ]

[ROM]
regions=[
    { name="audiocpu", start="JTFRAME_BA1_START" },
    { name="chars", start="JTFRAME_BA2_START", reverse=true },
    { name="sprites", width=16, sequence=[3,0,4,1,5,2] },
    { name="tiles", width=32, sequence=[0,2,4,4,1,3,5,5], start="JTFRAME_BA3_START" },
    { name="plds", skip=true },
]

order=[ "maincpu", "audiocpu", "chars",
    "sprites", "tiles", "proms" ]