set_global_assignment -name VERILOG_MACRO "CORENAME=\"JT1942\""
set_global_assignment -name VERILOG_MACRO "GAMETOP=jt1942_game"
set_global_assignment -name VERILOG_MACRO "VERTICAL_SCREEN=1"
set_global_assignment -name VERILOG_MACRO "JTFRAME_MRA_DIP=1"
set_global_assignment -name VERILOG_MACRO "SIGNED_SND=0"
set_global_assignment -name VERILOG_MACRO "JTFRAME_ARX=5"
set_global_assignment -name VERILOG_MACRO "JTFRAME_ARY=4"
set_global_assignment -name VERILOG_MACRO "BUTTONS=2"
