[global]
author=["jotego"]

[features]
# debug=true

[parse]
sourcefile=[ "ddribble.cpp" ]

[buttons]
names=[
    { names="Pass,Shoot,Steal" }
]

[dipsw]
delete=[{ names=["Unused","Unknown"] }]

[ROM]
regions = [
    { name="maincpu"  },
    { name="subcpu"   },
    { name="audiocpu" },
    { name="vlm"      },
    { name="gfx1", width=16, no_offset=true },
    { name="gfx2", width=16, no_offset=true },
    { name="proms", start="JTFRAME_PROM_START" },
]

order = [
    "maincpu", "subcpu", "audiocpu", "vlm", "gfx1", "gfx2", "proms"
]
