name: Run core simulations

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  list_setnames:
    runs-on: ubuntu-24.04
    outputs:
      pairs: ${{ steps.get.outputs.result }}
    steps:
      - uses: actions/checkout@v4

      - name: Get core/setname pairs
        id: get
        uses: mikefarah/yq@v4
        with:
          cmd: >
            yq ea -o=json -I=0 '
              [
                to_entries[]
                | .key as $core
                | (.value // {} | to_entries[]
                  | .key) as $sn
                | {"core": $core, "setname": $sn}
              ] | unique
            ' cores/*/cfg/regression.yaml

  simulate:
    name: Simulate ${{ matrix.setname }}
    runs-on: ubuntu-24.04
    container:
      image: jotego/simulator
    needs:
      - list_setnames

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.list_setnames.outputs.pairs) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Start ssh-agent and add key
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-add ~/.ssh/id_ed25519

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SSH_PORT }}" "${{ secrets.SERVER_IP }}" >> ~/.ssh/known_hosts

      - name: Run simulation
        run: |
          mkdir -p ~/.mame/roms
          bash -c 'source setprj.sh && run_regression.sh ${{ matrix.core }} ${{ matrix.setname }} --check --push --port "${{ secrets.SSH_PORT }}" --user "${{ secrets.SFTP_USER }}" --host "${{ secrets.SERVER_IP }}"'
          