name: Run core simulations

on:
  workflow_dispatch:
  # pull_request:
  # repository_dispatch:
  #   types: [rebuild]
  # push:
  #   branches:
  #     - master

jobs:
  simulate:
    name: Simulate ${{ matrix.core }}
    runs-on: ubuntu-24.04
    container:
      image: jotego/simulator

    strategy:
      matrix:
        core:
          - 1942
          - aliens

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Run simulation
        run: pwd
        # run: ./run_simulation.sh ${{ matrix.core }}