name: Run core simulations

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  list_cores:
    runs-on: ubuntu-24.04
    defaults:
      run:
        shell: bash
    outputs:
      cores: ${{ steps.generate-matrix.outputs.cores }}
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
        token: ${{ secrets.PAT }}
    - id: generate-matrix
      run: |
        cd cores
        # Get list of cores ready for regression
        CORES='['
        for i in *; do
          if [[ -e $i/cfg/.regression ]]; then
            if [ "$CORES" != '[' ]; then CORES="$CORES, "; fi
            CORES="$CORES \"$i\""
          fi
        done
        CORES="$CORES ]"
        echo $CORES
        echo "cores=${CORES}" >> $GITHUB_OUTPUT

  simulate:
    name: Simulate ${{ matrix.core }}
    runs-on: ubuntu-24.04
    container:
      image: jotego/simulator
    needs:
      - list_cores

    strategy:
      matrix:
        core: ${{ fromJSON(needs.list_cores.outputs.cores) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Start ssh-agent and add key
        run: |
          eval "$(ssh-agent -s)"
          mkdir -p ~/.ssh
          echo "${{ secrets.SFTP_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-add ~/.ssh/id_ed25519

      - name: Add server to known_hosts
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -p "${{ secrets.SFTP_PORT }}" "${{ secrets.SFTP_HOST }}" >> ~/.ssh/known_hosts

      - name: Run simulation
        run: |
          mkdir -p ~/.mame/roms
          bash -c 'source setprj.sh && run_simulation.sh ${{ matrix.core }} --check'