name: Run core regressions

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - master

jobs:
  list_setnames:
    runs-on: ubuntu-24.04
    outputs:
      pairs: ${{ steps.get.outputs.result }}
    steps:
      - uses: actions/checkout@v4

      - name: Get core/setname pairs
        id: get
        uses: mikefarah/yq@v4
        with:
          cmd: >
            yq ea -o=json -I=0 '
              [
                to_entries[]
                | .key as $core
                | (.value // {} | to_entries[]
                  | .key) as $sn
                | {"core": $core, "setname": $sn}
              ] | unique
            ' cores/*/cfg/regression.yaml

  simulate:
    name: Simulate ${{ matrix.setname }}
    runs-on: ubuntu-24.04
    container:
      image: jotego/simulator
    needs:
      - list_setnames

    strategy:
      fail-fast: false
      matrix:
        include: ${{ fromJSON(needs.list_setnames.outputs.pairs) }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.PAT }}

      - name: Setup SSH key
        uses: webfactory/ssh-agent@v0.9.1
        with:
          ssh-private-key: ${{ secrets.SFTP_PRIVATE_KEY }}

      - name: Add server to known_hosts
        run: |
          ssh-keyscan -H -p "${{ secrets.SSH_PORT }}" "${{ secrets.SERVER_IP }}" >> /etc/ssh/ssh_known_hosts

      - name: Run regression
        run: |
          mkdir -p ~/.mame/roms
          git config --global --add safe.directory /__w/jtcores/jtcores
          git config --global --add safe.directory /__w/jtcores/jtcores/modules/jtframe/target/pocket
          bash -c 'source setprj.sh && run_regression.sh ${{ matrix.core }} ${{ matrix.setname }} --check --push --port "${{ secrets.SSH_PORT }}" --user "${{ secrets.SSH_USER }}" --host "${{ secrets.SERVER_IP }}"'
          