name: Verilator native tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'modules/jtframe/verilator/**'
      - '.github/workflows/verilator-tests.yaml'
  push:
    branches:
      - master
    paths:
      - 'modules/jtframe/verilator/**'
      - '.github/workflows/verilator-tests.yaml'

jobs:
  verilator_tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        token: ${{secrets.PAT}}
    - name: Run native Verilator tests
      run: docker run --network host -v `pwd`:/jtcores jotego/linter make -C /jtcores/modules/jtframe/verilator/tests test
