#!/bin/bash
TOP=test

verilator ../../hdl/jtcps2_sbox.v $TOP.v -cc test.cc cps2crypt.cpp -exe --top-module test
export CPPFLAGS="$CPPFLAGS -O2"



if ! make -j -C obj_dir -f V${TOP}.mk V${TOP} > make.log; then
    cat make.log
    exit $?
else
    rm make.log
fi

obj_dir/V$TOP
